#############################################################################
# Makefile for building: TheLittlreRocksGame
# Generated by qmake (3.0) (Qt 5.1.1) on: sam. déc. 14 14:22:54 2013
# Project:  TheLittlreRocksGame.pro
# Template: app
# Command: /home/cyril/android/qt/5.1.1/gcc/bin/qmake -spec linux-g++ -o Makefile TheLittlreRocksGame.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_MULTIMEDIA_LIB -DQT_WIDGETS_LIB -DQT_NETWORK_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I../android/qt/5.1.1/gcc/mkspecs/linux-g++ -I. -I../android/qt/5.1.1/gcc/include -I../android/qt/5.1.1/gcc/include/QtMultimedia -I../android/qt/5.1.1/gcc/include/QtWidgets -I../android/qt/5.1.1/gcc/include/QtNetwork -I../android/qt/5.1.1/gcc/include/QtGui -I../android/qt/5.1.1/gcc/include/QtCore -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/cyril/android/qt/5.1.1/gcc -Wl,-rpath,/home/cyril/android/qt/5.1.1/gcc/lib
LIBS          = $(SUBLIBS) -L/home/cyril/android/qt/5.1.1/gcc/lib -lQt5Multimedia -lQt5Widgets -lQt5Network -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/cyril/android/qt/5.1.1/gcc/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		pierre.cpp \
		dialogtheme.cpp \
		dialogoption.cpp qrc_Images.cpp \
		moc_mainwindow.cpp \
		moc_pierre.cpp \
		moc_dialogtheme.cpp \
		moc_dialogoption.cpp
OBJECTS       = main.o \
		mainwindow.o \
		pierre.o \
		dialogtheme.o \
		dialogoption.o \
		qrc_Images.o \
		moc_mainwindow.o \
		moc_pierre.o \
		moc_dialogtheme.o \
		moc_dialogoption.o
DIST          = ../android/qt/5.1.1/gcc/mkspecs/features/spec_pre.prf \
		../android/qt/5.1.1/gcc/mkspecs/common/shell-unix.conf \
		../android/qt/5.1.1/gcc/mkspecs/common/unix.conf \
		../android/qt/5.1.1/gcc/mkspecs/common/linux.conf \
		../android/qt/5.1.1/gcc/mkspecs/common/gcc-base.conf \
		../android/qt/5.1.1/gcc/mkspecs/common/gcc-base-unix.conf \
		../android/qt/5.1.1/gcc/mkspecs/common/g++-base.conf \
		../android/qt/5.1.1/gcc/mkspecs/common/g++-unix.conf \
		../android/qt/5.1.1/gcc/mkspecs/qconfig.pri \
		../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_clucene.pri \
		../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_concurrent.pri \
		../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_core.pri \
		../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_dbus.pri \
		../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_declarative.pri \
		../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_designer.pri \
		../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_designercomponents.pri \
		../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_gui.pri \
		../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_help.pri \
		../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_multimedia.pri \
		../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_network.pri \
		../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_opengl.pri \
		../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_openglextensions.pri \
		../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_platformsupport.pri \
		../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_printsupport.pri \
		../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_qml.pri \
		../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_qmldevtools.pri \
		../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_qmltest.pri \
		../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_quick.pri \
		../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_quickparticles.pri \
		../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_script.pri \
		../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_scripttools.pri \
		../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_sensors.pri \
		../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_serialport.pri \
		../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_sql.pri \
		../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_svg.pri \
		../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_testlib.pri \
		../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_uitools.pri \
		../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_v8.pri \
		../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_webkit.pri \
		../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_widgets.pri \
		../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_x11extras.pri \
		../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_xml.pri \
		../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../android/qt/5.1.1/gcc/mkspecs/features/qt_functions.prf \
		../android/qt/5.1.1/gcc/mkspecs/features/qt_config.prf \
		../android/qt/5.1.1/gcc/mkspecs/linux-g++/qmake.conf \
		../android/qt/5.1.1/gcc/mkspecs/features/spec_post.prf \
		../android/qt/5.1.1/gcc/mkspecs/features/exclusive_builds.prf \
		../android/qt/5.1.1/gcc/mkspecs/features/default_pre.prf \
		../android/qt/5.1.1/gcc/mkspecs/features/unix/default_pre.prf \
		../android/qt/5.1.1/gcc/mkspecs/features/resolve_config.prf \
		../android/qt/5.1.1/gcc/mkspecs/features/default_post.prf \
		../android/qt/5.1.1/gcc/mkspecs/features/unix/gdb_dwarf_index.prf \
		../android/qt/5.1.1/gcc/mkspecs/features/warn_on.prf \
		../android/qt/5.1.1/gcc/mkspecs/features/qt.prf \
		../android/qt/5.1.1/gcc/mkspecs/features/resources.prf \
		../android/qt/5.1.1/gcc/mkspecs/features/moc.prf \
		../android/qt/5.1.1/gcc/mkspecs/features/unix/opengl.prf \
		../android/qt/5.1.1/gcc/mkspecs/features/uic.prf \
		../android/qt/5.1.1/gcc/mkspecs/features/unix/thread.prf \
		../android/qt/5.1.1/gcc/mkspecs/features/wayland-scanner.prf \
		../android/qt/5.1.1/gcc/mkspecs/features/testcase_targets.prf \
		../android/qt/5.1.1/gcc/mkspecs/features/exceptions.prf \
		../android/qt/5.1.1/gcc/mkspecs/features/yacc.prf \
		../android/qt/5.1.1/gcc/mkspecs/features/lex.prf \
		TheLittlreRocksGame.pro \
		Images.qrc \
		TheLittlreRocksGame.pro
QMAKE_TARGET  = TheLittlreRocksGame
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = TheLittlreRocksGame


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_dialogtheme.h ui_dialogoption.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: TheLittlreRocksGame.pro ../android/qt/5.1.1/gcc/mkspecs/linux-g++/qmake.conf ../android/qt/5.1.1/gcc/mkspecs/features/spec_pre.prf \
		../android/qt/5.1.1/gcc/mkspecs/common/shell-unix.conf \
		../android/qt/5.1.1/gcc/mkspecs/common/unix.conf \
		../android/qt/5.1.1/gcc/mkspecs/common/linux.conf \
		../android/qt/5.1.1/gcc/mkspecs/common/gcc-base.conf \
		../android/qt/5.1.1/gcc/mkspecs/common/gcc-base-unix.conf \
		../android/qt/5.1.1/gcc/mkspecs/common/g++-base.conf \
		../android/qt/5.1.1/gcc/mkspecs/common/g++-unix.conf \
		../android/qt/5.1.1/gcc/mkspecs/qconfig.pri \
		../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_clucene.pri \
		../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_concurrent.pri \
		../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_core.pri \
		../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_dbus.pri \
		../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_declarative.pri \
		../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_designer.pri \
		../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_designercomponents.pri \
		../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_gui.pri \
		../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_help.pri \
		../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_multimedia.pri \
		../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_network.pri \
		../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_opengl.pri \
		../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_openglextensions.pri \
		../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_platformsupport.pri \
		../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_printsupport.pri \
		../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_qml.pri \
		../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_qmldevtools.pri \
		../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_qmltest.pri \
		../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_quick.pri \
		../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_quickparticles.pri \
		../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_script.pri \
		../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_scripttools.pri \
		../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_sensors.pri \
		../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_serialport.pri \
		../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_sql.pri \
		../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_svg.pri \
		../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_testlib.pri \
		../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_uitools.pri \
		../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_v8.pri \
		../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_webkit.pri \
		../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_widgets.pri \
		../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_x11extras.pri \
		../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_xml.pri \
		../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../android/qt/5.1.1/gcc/mkspecs/features/qt_functions.prf \
		../android/qt/5.1.1/gcc/mkspecs/features/qt_config.prf \
		../android/qt/5.1.1/gcc/mkspecs/linux-g++/qmake.conf \
		../android/qt/5.1.1/gcc/mkspecs/features/spec_post.prf \
		../android/qt/5.1.1/gcc/mkspecs/features/exclusive_builds.prf \
		../android/qt/5.1.1/gcc/mkspecs/features/default_pre.prf \
		../android/qt/5.1.1/gcc/mkspecs/features/unix/default_pre.prf \
		../android/qt/5.1.1/gcc/mkspecs/features/resolve_config.prf \
		../android/qt/5.1.1/gcc/mkspecs/features/default_post.prf \
		../android/qt/5.1.1/gcc/mkspecs/features/unix/gdb_dwarf_index.prf \
		../android/qt/5.1.1/gcc/mkspecs/features/warn_on.prf \
		../android/qt/5.1.1/gcc/mkspecs/features/qt.prf \
		../android/qt/5.1.1/gcc/mkspecs/features/resources.prf \
		../android/qt/5.1.1/gcc/mkspecs/features/moc.prf \
		../android/qt/5.1.1/gcc/mkspecs/features/unix/opengl.prf \
		../android/qt/5.1.1/gcc/mkspecs/features/uic.prf \
		../android/qt/5.1.1/gcc/mkspecs/features/unix/thread.prf \
		../android/qt/5.1.1/gcc/mkspecs/features/wayland-scanner.prf \
		../android/qt/5.1.1/gcc/mkspecs/features/testcase_targets.prf \
		../android/qt/5.1.1/gcc/mkspecs/features/exceptions.prf \
		../android/qt/5.1.1/gcc/mkspecs/features/yacc.prf \
		../android/qt/5.1.1/gcc/mkspecs/features/lex.prf \
		TheLittlreRocksGame.pro \
		Images.qrc \
		/home/cyril/android/qt/5.1.1/gcc/lib/libQt5Multimedia.prl \
		/home/cyril/android/qt/5.1.1/gcc/lib/libQt5Widgets.prl \
		/home/cyril/android/qt/5.1.1/gcc/lib/libQt5Network.prl \
		/home/cyril/android/qt/5.1.1/gcc/lib/libQt5Gui.prl \
		/home/cyril/android/qt/5.1.1/gcc/lib/libQt5Core.prl
	$(QMAKE) -spec linux-g++ -o Makefile TheLittlreRocksGame.pro
../android/qt/5.1.1/gcc/mkspecs/features/spec_pre.prf:
../android/qt/5.1.1/gcc/mkspecs/common/shell-unix.conf:
../android/qt/5.1.1/gcc/mkspecs/common/unix.conf:
../android/qt/5.1.1/gcc/mkspecs/common/linux.conf:
../android/qt/5.1.1/gcc/mkspecs/common/gcc-base.conf:
../android/qt/5.1.1/gcc/mkspecs/common/gcc-base-unix.conf:
../android/qt/5.1.1/gcc/mkspecs/common/g++-base.conf:
../android/qt/5.1.1/gcc/mkspecs/common/g++-unix.conf:
../android/qt/5.1.1/gcc/mkspecs/qconfig.pri:
../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_clucene.pri:
../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_concurrent.pri:
../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_core.pri:
../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_dbus.pri:
../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_declarative.pri:
../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_designer.pri:
../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_designercomponents.pri:
../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_gui.pri:
../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_help.pri:
../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_multimedia.pri:
../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_multimediawidgets.pri:
../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_network.pri:
../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_opengl.pri:
../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_openglextensions.pri:
../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_platformsupport.pri:
../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_printsupport.pri:
../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_qml.pri:
../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_qmldevtools.pri:
../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_qmltest.pri:
../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri:
../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_quick.pri:
../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_quickparticles.pri:
../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_script.pri:
../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_scripttools.pri:
../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_sensors.pri:
../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_serialport.pri:
../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_sql.pri:
../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_svg.pri:
../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_testlib.pri:
../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_uitools.pri:
../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_v8.pri:
../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_webkit.pri:
../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_webkitwidgets.pri:
../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_widgets.pri:
../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_x11extras.pri:
../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_xml.pri:
../android/qt/5.1.1/gcc/mkspecs/modules/qt_lib_xmlpatterns.pri:
../android/qt/5.1.1/gcc/mkspecs/features/qt_functions.prf:
../android/qt/5.1.1/gcc/mkspecs/features/qt_config.prf:
../android/qt/5.1.1/gcc/mkspecs/linux-g++/qmake.conf:
../android/qt/5.1.1/gcc/mkspecs/features/spec_post.prf:
../android/qt/5.1.1/gcc/mkspecs/features/exclusive_builds.prf:
../android/qt/5.1.1/gcc/mkspecs/features/default_pre.prf:
../android/qt/5.1.1/gcc/mkspecs/features/unix/default_pre.prf:
../android/qt/5.1.1/gcc/mkspecs/features/resolve_config.prf:
../android/qt/5.1.1/gcc/mkspecs/features/default_post.prf:
../android/qt/5.1.1/gcc/mkspecs/features/unix/gdb_dwarf_index.prf:
../android/qt/5.1.1/gcc/mkspecs/features/warn_on.prf:
../android/qt/5.1.1/gcc/mkspecs/features/qt.prf:
../android/qt/5.1.1/gcc/mkspecs/features/resources.prf:
../android/qt/5.1.1/gcc/mkspecs/features/moc.prf:
../android/qt/5.1.1/gcc/mkspecs/features/unix/opengl.prf:
../android/qt/5.1.1/gcc/mkspecs/features/uic.prf:
../android/qt/5.1.1/gcc/mkspecs/features/unix/thread.prf:
../android/qt/5.1.1/gcc/mkspecs/features/wayland-scanner.prf:
../android/qt/5.1.1/gcc/mkspecs/features/testcase_targets.prf:
../android/qt/5.1.1/gcc/mkspecs/features/exceptions.prf:
../android/qt/5.1.1/gcc/mkspecs/features/yacc.prf:
../android/qt/5.1.1/gcc/mkspecs/features/lex.prf:
TheLittlreRocksGame.pro:
Images.qrc:
/home/cyril/android/qt/5.1.1/gcc/lib/libQt5Multimedia.prl:
/home/cyril/android/qt/5.1.1/gcc/lib/libQt5Widgets.prl:
/home/cyril/android/qt/5.1.1/gcc/lib/libQt5Network.prl:
/home/cyril/android/qt/5.1.1/gcc/lib/libQt5Gui.prl:
/home/cyril/android/qt/5.1.1/gcc/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ -o Makefile TheLittlreRocksGame.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/TheLittlreRocksGame1.0.0 || mkdir -p .tmp/TheLittlreRocksGame1.0.0
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/TheLittlreRocksGame1.0.0/ && $(COPY_FILE) --parents Images.qrc .tmp/TheLittlreRocksGame1.0.0/ && $(COPY_FILE) --parents mainwindow.h pierre.h dialogtheme.h dialogoption.h .tmp/TheLittlreRocksGame1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp pierre.cpp dialogtheme.cpp dialogoption.cpp .tmp/TheLittlreRocksGame1.0.0/ && $(COPY_FILE) --parents mainwindow.ui dialogtheme.ui dialogoption.ui .tmp/TheLittlreRocksGame1.0.0/ && (cd `dirname .tmp/TheLittlreRocksGame1.0.0` && $(TAR) TheLittlreRocksGame1.0.0.tar TheLittlreRocksGame1.0.0 && $(COMPRESS) TheLittlreRocksGame1.0.0.tar) && $(MOVE) `dirname .tmp/TheLittlreRocksGame1.0.0`/TheLittlreRocksGame1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/TheLittlreRocksGame1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all: qrc_Images.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_Images.cpp
qrc_Images.cpp: Images.qrc \
		minecraft/craft1.png \
		minecraft/craft2.png \
		marioOk.wav \
		mordor.jpg \
		neonNon.wav \
		plateauHerbe.png \
		golfNon.wav \
		victoire2.wav \
		plateau-mario.png \
		plateau-mario.gif \
		yeees2.wav \
		victoire.gif \
		suspens.wav \
		golf1.png \
		golfOk.wav \
		golf2.png \
		minecraft/plateau-craft.png \
		neonOk.wav \
		ring1.png \
		ring2.png \
		mario1.png \
		mario2.png \
		hooo2.wav \
		plateau.jpg \
		plateauNeon.png \
		mario-fin.wav \
		pierre1.png \
		pierre2.png \
		marioNon.wav
	/home/cyril/android/qt/5.1.1/gcc/bin/rcc -name Images Images.qrc -o qrc_Images.cpp

compiler_wayland_server_header_make_all:
compiler_wayland_server_header_clean:
compiler_wayland_client_header_make_all:
compiler_wayland_client_header_clean:
compiler_qtwayland_client_header_make_all:
compiler_qtwayland_client_header_clean:
compiler_qtwayland_server_header_make_all:
compiler_qtwayland_server_header_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp moc_pierre.cpp moc_dialogtheme.cpp moc_dialogoption.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_pierre.cpp moc_dialogtheme.cpp moc_dialogoption.cpp
moc_mainwindow.cpp: ../android/qt/5.1.1/gcc/include/QtWidgets/QMainWindow \
		../android/qt/5.1.1/gcc/include/QtWidgets/qmainwindow.h \
		../android/qt/5.1.1/gcc/include/QtWidgets/qwidget.h \
		../android/qt/5.1.1/gcc/include/QtGui/qwindowdefs.h \
		../android/qt/5.1.1/gcc/include/QtCore/qglobal.h \
		../android/qt/5.1.1/gcc/include/QtCore/qconfig.h \
		../android/qt/5.1.1/gcc/include/QtCore/qfeatures.h \
		../android/qt/5.1.1/gcc/include/QtCore/qsystemdetection.h \
		../android/qt/5.1.1/gcc/include/QtCore/qcompilerdetection.h \
		../android/qt/5.1.1/gcc/include/QtCore/qprocessordetection.h \
		../android/qt/5.1.1/gcc/include/QtCore/qglobalstatic.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic.h \
		../android/qt/5.1.1/gcc/include/QtCore/qbasicatomic.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_bootstrap.h \
		../android/qt/5.1.1/gcc/include/QtCore/qgenericatomic.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_msvc.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_integrity.h \
		../android/qt/5.1.1/gcc/include/QtCore/qoldbasicatomic.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_vxworks.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_power.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_alpha.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_armv7.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_armv6.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_armv5.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_bfin.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_ia64.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_mips.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_s390.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_sh4a.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_sparc.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_x86.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_cxx11.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_gcc.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_unix.h \
		../android/qt/5.1.1/gcc/include/QtCore/qmutex.h \
		../android/qt/5.1.1/gcc/include/QtCore/qlogging.h \
		../android/qt/5.1.1/gcc/include/QtCore/qflags.h \
		../android/qt/5.1.1/gcc/include/QtCore/qtypeinfo.h \
		../android/qt/5.1.1/gcc/include/QtCore/qtypetraits.h \
		../android/qt/5.1.1/gcc/include/QtCore/qsysinfo.h \
		../android/qt/5.1.1/gcc/include/QtCore/qobjectdefs.h \
		../android/qt/5.1.1/gcc/include/QtCore/qnamespace.h \
		../android/qt/5.1.1/gcc/include/QtCore/qobjectdefs_impl.h \
		../android/qt/5.1.1/gcc/include/QtGui/qwindowdefs_win.h \
		../android/qt/5.1.1/gcc/include/QtCore/qobject.h \
		../android/qt/5.1.1/gcc/include/QtCore/qstring.h \
		../android/qt/5.1.1/gcc/include/QtCore/qchar.h \
		../android/qt/5.1.1/gcc/include/QtCore/qbytearray.h \
		../android/qt/5.1.1/gcc/include/QtCore/qrefcount.h \
		../android/qt/5.1.1/gcc/include/QtCore/qarraydata.h \
		../android/qt/5.1.1/gcc/include/QtCore/qstringbuilder.h \
		../android/qt/5.1.1/gcc/include/QtCore/qlist.h \
		../android/qt/5.1.1/gcc/include/QtCore/qalgorithms.h \
		../android/qt/5.1.1/gcc/include/QtCore/qiterator.h \
		../android/qt/5.1.1/gcc/include/QtCore/qcoreevent.h \
		../android/qt/5.1.1/gcc/include/QtCore/qscopedpointer.h \
		../android/qt/5.1.1/gcc/include/QtCore/qmetatype.h \
		../android/qt/5.1.1/gcc/include/QtCore/qvarlengtharray.h \
		../android/qt/5.1.1/gcc/include/QtCore/qcontainerfwd.h \
		../android/qt/5.1.1/gcc/include/QtCore/qisenum.h \
		../android/qt/5.1.1/gcc/include/QtCore/qobject_impl.h \
		../android/qt/5.1.1/gcc/include/QtCore/qmargins.h \
		../android/qt/5.1.1/gcc/include/QtCore/qrect.h \
		../android/qt/5.1.1/gcc/include/QtCore/qsize.h \
		../android/qt/5.1.1/gcc/include/QtCore/qpoint.h \
		../android/qt/5.1.1/gcc/include/QtGui/qpaintdevice.h \
		../android/qt/5.1.1/gcc/include/QtGui/qpalette.h \
		../android/qt/5.1.1/gcc/include/QtGui/qcolor.h \
		../android/qt/5.1.1/gcc/include/QtGui/qrgb.h \
		../android/qt/5.1.1/gcc/include/QtCore/qstringlist.h \
		../android/qt/5.1.1/gcc/include/QtCore/qdatastream.h \
		../android/qt/5.1.1/gcc/include/QtCore/qiodevice.h \
		../android/qt/5.1.1/gcc/include/QtCore/qpair.h \
		../android/qt/5.1.1/gcc/include/QtCore/qregexp.h \
		../android/qt/5.1.1/gcc/include/QtCore/qstringmatcher.h \
		../android/qt/5.1.1/gcc/include/QtGui/qbrush.h \
		../android/qt/5.1.1/gcc/include/QtCore/qvector.h \
		../android/qt/5.1.1/gcc/include/QtGui/qmatrix.h \
		../android/qt/5.1.1/gcc/include/QtGui/qpolygon.h \
		../android/qt/5.1.1/gcc/include/QtGui/qregion.h \
		../android/qt/5.1.1/gcc/include/QtCore/qline.h \
		../android/qt/5.1.1/gcc/include/QtGui/qtransform.h \
		../android/qt/5.1.1/gcc/include/QtGui/qpainterpath.h \
		../android/qt/5.1.1/gcc/include/QtGui/qimage.h \
		../android/qt/5.1.1/gcc/include/QtGui/qpixmap.h \
		../android/qt/5.1.1/gcc/include/QtCore/qsharedpointer.h \
		../android/qt/5.1.1/gcc/include/QtCore/qshareddata.h \
		../android/qt/5.1.1/gcc/include/QtCore/qsharedpointer_impl.h \
		../android/qt/5.1.1/gcc/include/QtCore/qhash.h \
		../android/qt/5.1.1/gcc/include/QtGui/qfont.h \
		../android/qt/5.1.1/gcc/include/QtGui/qfontmetrics.h \
		../android/qt/5.1.1/gcc/include/QtGui/qfontinfo.h \
		../android/qt/5.1.1/gcc/include/QtWidgets/qsizepolicy.h \
		../android/qt/5.1.1/gcc/include/QtGui/qcursor.h \
		../android/qt/5.1.1/gcc/include/QtGui/qkeysequence.h \
		../android/qt/5.1.1/gcc/include/QtGui/qevent.h \
		../android/qt/5.1.1/gcc/include/QtCore/qvariant.h \
		../android/qt/5.1.1/gcc/include/QtCore/qmap.h \
		../android/qt/5.1.1/gcc/include/QtCore/qdebug.h \
		../android/qt/5.1.1/gcc/include/QtCore/qtextstream.h \
		../android/qt/5.1.1/gcc/include/QtCore/qlocale.h \
		../android/qt/5.1.1/gcc/include/QtCore/qset.h \
		../android/qt/5.1.1/gcc/include/QtCore/qcontiguouscache.h \
		../android/qt/5.1.1/gcc/include/QtCore/qurl.h \
		../android/qt/5.1.1/gcc/include/QtCore/qurlquery.h \
		../android/qt/5.1.1/gcc/include/QtCore/qfile.h \
		../android/qt/5.1.1/gcc/include/QtCore/qfiledevice.h \
		../android/qt/5.1.1/gcc/include/QtGui/qvector2d.h \
		../android/qt/5.1.1/gcc/include/QtGui/qtouchdevice.h \
		../android/qt/5.1.1/gcc/include/QtWidgets/qtabwidget.h \
		../android/qt/5.1.1/gcc/include/QtGui/qicon.h \
		../android/qt/5.1.1/gcc/include/QtCore/QDebug \
		../android/qt/5.1.1/gcc/include/QtGui/QPainter \
		../android/qt/5.1.1/gcc/include/QtGui/qpainter.h \
		../android/qt/5.1.1/gcc/include/QtGui/qtextoption.h \
		../android/qt/5.1.1/gcc/include/QtGui/qpen.h \
		../android/qt/5.1.1/gcc/include/QtCore/QRectF \
		pierre.h \
		../android/qt/5.1.1/gcc/include/QtWidgets/QLabel \
		../android/qt/5.1.1/gcc/include/QtWidgets/qlabel.h \
		../android/qt/5.1.1/gcc/include/QtWidgets/qframe.h \
		../android/qt/5.1.1/gcc/include/QtGui/QMouseEvent \
		../android/qt/5.1.1/gcc/include/QtCore/QVector \
		../android/qt/5.1.1/gcc/include/QtGui/QMovie \
		../android/qt/5.1.1/gcc/include/QtGui/qmovie.h \
		../android/qt/5.1.1/gcc/include/QtGui/qimagereader.h \
		../android/qt/5.1.1/gcc/include/QtGui/qimageiohandler.h \
		../android/qt/5.1.1/gcc/include/QtCore/qplugin.h \
		../android/qt/5.1.1/gcc/include/QtCore/qpointer.h \
		../android/qt/5.1.1/gcc/include/QtCore/qfactoryinterface.h \
		../android/qt/5.1.1/gcc/include/QtMultimedia/QMediaPlayer \
		../android/qt/5.1.1/gcc/include/QtMultimedia/qmediaplayer.h \
		../android/qt/5.1.1/gcc/include/QtMultimedia/qmediaobject.h \
		../android/qt/5.1.1/gcc/include/QtMultimedia/qtmultimediadefs.h \
		../android/qt/5.1.1/gcc/include/QtMultimedia/qmultimedia.h \
		../android/qt/5.1.1/gcc/include/QtMultimedia/qmediacontent.h \
		../android/qt/5.1.1/gcc/include/QtMultimedia/qmediaresource.h \
		../android/qt/5.1.1/gcc/include/QtNetwork/qnetworkrequest.h \
		../android/qt/5.1.1/gcc/include/QtCore/QSharedDataPointer \
		../android/qt/5.1.1/gcc/include/QtCore/QString \
		../android/qt/5.1.1/gcc/include/QtCore/QUrl \
		../android/qt/5.1.1/gcc/include/QtCore/QVariant \
		../android/qt/5.1.1/gcc/include/QtMultimedia/qmediaenumdebug.h \
		../android/qt/5.1.1/gcc/include/QtCore/qmetaobject.h \
		../android/qt/5.1.1/gcc/include/QtNetwork/qnetworkconfiguration.h \
		../android/qt/5.1.1/gcc/include/QtMultimedia/QSoundEffect \
		../android/qt/5.1.1/gcc/include/QtMultimedia/qsoundeffect.h \
		dialogtheme.h \
		../android/qt/5.1.1/gcc/include/QtWidgets/QDialog \
		../android/qt/5.1.1/gcc/include/QtWidgets/qdialog.h \
		mainwindow.h \
		dialogoption.h \
		../android/qt/5.1.1/gcc/include/QtGui/QPixmap \
		mainwindow.h
	/home/cyril/android/qt/5.1.1/gcc/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_pierre.cpp: ../android/qt/5.1.1/gcc/include/QtWidgets/QLabel \
		../android/qt/5.1.1/gcc/include/QtWidgets/qlabel.h \
		../android/qt/5.1.1/gcc/include/QtWidgets/qframe.h \
		../android/qt/5.1.1/gcc/include/QtWidgets/qwidget.h \
		../android/qt/5.1.1/gcc/include/QtGui/qwindowdefs.h \
		../android/qt/5.1.1/gcc/include/QtCore/qglobal.h \
		../android/qt/5.1.1/gcc/include/QtCore/qconfig.h \
		../android/qt/5.1.1/gcc/include/QtCore/qfeatures.h \
		../android/qt/5.1.1/gcc/include/QtCore/qsystemdetection.h \
		../android/qt/5.1.1/gcc/include/QtCore/qcompilerdetection.h \
		../android/qt/5.1.1/gcc/include/QtCore/qprocessordetection.h \
		../android/qt/5.1.1/gcc/include/QtCore/qglobalstatic.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic.h \
		../android/qt/5.1.1/gcc/include/QtCore/qbasicatomic.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_bootstrap.h \
		../android/qt/5.1.1/gcc/include/QtCore/qgenericatomic.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_msvc.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_integrity.h \
		../android/qt/5.1.1/gcc/include/QtCore/qoldbasicatomic.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_vxworks.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_power.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_alpha.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_armv7.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_armv6.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_armv5.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_bfin.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_ia64.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_mips.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_s390.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_sh4a.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_sparc.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_x86.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_cxx11.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_gcc.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_unix.h \
		../android/qt/5.1.1/gcc/include/QtCore/qmutex.h \
		../android/qt/5.1.1/gcc/include/QtCore/qlogging.h \
		../android/qt/5.1.1/gcc/include/QtCore/qflags.h \
		../android/qt/5.1.1/gcc/include/QtCore/qtypeinfo.h \
		../android/qt/5.1.1/gcc/include/QtCore/qtypetraits.h \
		../android/qt/5.1.1/gcc/include/QtCore/qsysinfo.h \
		../android/qt/5.1.1/gcc/include/QtCore/qobjectdefs.h \
		../android/qt/5.1.1/gcc/include/QtCore/qnamespace.h \
		../android/qt/5.1.1/gcc/include/QtCore/qobjectdefs_impl.h \
		../android/qt/5.1.1/gcc/include/QtGui/qwindowdefs_win.h \
		../android/qt/5.1.1/gcc/include/QtCore/qobject.h \
		../android/qt/5.1.1/gcc/include/QtCore/qstring.h \
		../android/qt/5.1.1/gcc/include/QtCore/qchar.h \
		../android/qt/5.1.1/gcc/include/QtCore/qbytearray.h \
		../android/qt/5.1.1/gcc/include/QtCore/qrefcount.h \
		../android/qt/5.1.1/gcc/include/QtCore/qarraydata.h \
		../android/qt/5.1.1/gcc/include/QtCore/qstringbuilder.h \
		../android/qt/5.1.1/gcc/include/QtCore/qlist.h \
		../android/qt/5.1.1/gcc/include/QtCore/qalgorithms.h \
		../android/qt/5.1.1/gcc/include/QtCore/qiterator.h \
		../android/qt/5.1.1/gcc/include/QtCore/qcoreevent.h \
		../android/qt/5.1.1/gcc/include/QtCore/qscopedpointer.h \
		../android/qt/5.1.1/gcc/include/QtCore/qmetatype.h \
		../android/qt/5.1.1/gcc/include/QtCore/qvarlengtharray.h \
		../android/qt/5.1.1/gcc/include/QtCore/qcontainerfwd.h \
		../android/qt/5.1.1/gcc/include/QtCore/qisenum.h \
		../android/qt/5.1.1/gcc/include/QtCore/qobject_impl.h \
		../android/qt/5.1.1/gcc/include/QtCore/qmargins.h \
		../android/qt/5.1.1/gcc/include/QtCore/qrect.h \
		../android/qt/5.1.1/gcc/include/QtCore/qsize.h \
		../android/qt/5.1.1/gcc/include/QtCore/qpoint.h \
		../android/qt/5.1.1/gcc/include/QtGui/qpaintdevice.h \
		../android/qt/5.1.1/gcc/include/QtGui/qpalette.h \
		../android/qt/5.1.1/gcc/include/QtGui/qcolor.h \
		../android/qt/5.1.1/gcc/include/QtGui/qrgb.h \
		../android/qt/5.1.1/gcc/include/QtCore/qstringlist.h \
		../android/qt/5.1.1/gcc/include/QtCore/qdatastream.h \
		../android/qt/5.1.1/gcc/include/QtCore/qiodevice.h \
		../android/qt/5.1.1/gcc/include/QtCore/qpair.h \
		../android/qt/5.1.1/gcc/include/QtCore/qregexp.h \
		../android/qt/5.1.1/gcc/include/QtCore/qstringmatcher.h \
		../android/qt/5.1.1/gcc/include/QtGui/qbrush.h \
		../android/qt/5.1.1/gcc/include/QtCore/qvector.h \
		../android/qt/5.1.1/gcc/include/QtGui/qmatrix.h \
		../android/qt/5.1.1/gcc/include/QtGui/qpolygon.h \
		../android/qt/5.1.1/gcc/include/QtGui/qregion.h \
		../android/qt/5.1.1/gcc/include/QtCore/qline.h \
		../android/qt/5.1.1/gcc/include/QtGui/qtransform.h \
		../android/qt/5.1.1/gcc/include/QtGui/qpainterpath.h \
		../android/qt/5.1.1/gcc/include/QtGui/qimage.h \
		../android/qt/5.1.1/gcc/include/QtGui/qpixmap.h \
		../android/qt/5.1.1/gcc/include/QtCore/qsharedpointer.h \
		../android/qt/5.1.1/gcc/include/QtCore/qshareddata.h \
		../android/qt/5.1.1/gcc/include/QtCore/qsharedpointer_impl.h \
		../android/qt/5.1.1/gcc/include/QtCore/qhash.h \
		../android/qt/5.1.1/gcc/include/QtGui/qfont.h \
		../android/qt/5.1.1/gcc/include/QtGui/qfontmetrics.h \
		../android/qt/5.1.1/gcc/include/QtGui/qfontinfo.h \
		../android/qt/5.1.1/gcc/include/QtWidgets/qsizepolicy.h \
		../android/qt/5.1.1/gcc/include/QtGui/qcursor.h \
		../android/qt/5.1.1/gcc/include/QtGui/qkeysequence.h \
		../android/qt/5.1.1/gcc/include/QtGui/qevent.h \
		../android/qt/5.1.1/gcc/include/QtCore/qvariant.h \
		../android/qt/5.1.1/gcc/include/QtCore/qmap.h \
		../android/qt/5.1.1/gcc/include/QtCore/qdebug.h \
		../android/qt/5.1.1/gcc/include/QtCore/qtextstream.h \
		../android/qt/5.1.1/gcc/include/QtCore/qlocale.h \
		../android/qt/5.1.1/gcc/include/QtCore/qset.h \
		../android/qt/5.1.1/gcc/include/QtCore/qcontiguouscache.h \
		../android/qt/5.1.1/gcc/include/QtCore/qurl.h \
		../android/qt/5.1.1/gcc/include/QtCore/qurlquery.h \
		../android/qt/5.1.1/gcc/include/QtCore/qfile.h \
		../android/qt/5.1.1/gcc/include/QtCore/qfiledevice.h \
		../android/qt/5.1.1/gcc/include/QtGui/qvector2d.h \
		../android/qt/5.1.1/gcc/include/QtGui/qtouchdevice.h \
		../android/qt/5.1.1/gcc/include/QtGui/QMouseEvent \
		pierre.h
	/home/cyril/android/qt/5.1.1/gcc/bin/moc $(DEFINES) $(INCPATH) pierre.h -o moc_pierre.cpp

moc_dialogtheme.cpp: ../android/qt/5.1.1/gcc/include/QtWidgets/QDialog \
		../android/qt/5.1.1/gcc/include/QtWidgets/qdialog.h \
		../android/qt/5.1.1/gcc/include/QtWidgets/qwidget.h \
		../android/qt/5.1.1/gcc/include/QtGui/qwindowdefs.h \
		../android/qt/5.1.1/gcc/include/QtCore/qglobal.h \
		../android/qt/5.1.1/gcc/include/QtCore/qconfig.h \
		../android/qt/5.1.1/gcc/include/QtCore/qfeatures.h \
		../android/qt/5.1.1/gcc/include/QtCore/qsystemdetection.h \
		../android/qt/5.1.1/gcc/include/QtCore/qcompilerdetection.h \
		../android/qt/5.1.1/gcc/include/QtCore/qprocessordetection.h \
		../android/qt/5.1.1/gcc/include/QtCore/qglobalstatic.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic.h \
		../android/qt/5.1.1/gcc/include/QtCore/qbasicatomic.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_bootstrap.h \
		../android/qt/5.1.1/gcc/include/QtCore/qgenericatomic.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_msvc.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_integrity.h \
		../android/qt/5.1.1/gcc/include/QtCore/qoldbasicatomic.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_vxworks.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_power.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_alpha.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_armv7.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_armv6.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_armv5.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_bfin.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_ia64.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_mips.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_s390.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_sh4a.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_sparc.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_x86.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_cxx11.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_gcc.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_unix.h \
		../android/qt/5.1.1/gcc/include/QtCore/qmutex.h \
		../android/qt/5.1.1/gcc/include/QtCore/qlogging.h \
		../android/qt/5.1.1/gcc/include/QtCore/qflags.h \
		../android/qt/5.1.1/gcc/include/QtCore/qtypeinfo.h \
		../android/qt/5.1.1/gcc/include/QtCore/qtypetraits.h \
		../android/qt/5.1.1/gcc/include/QtCore/qsysinfo.h \
		../android/qt/5.1.1/gcc/include/QtCore/qobjectdefs.h \
		../android/qt/5.1.1/gcc/include/QtCore/qnamespace.h \
		../android/qt/5.1.1/gcc/include/QtCore/qobjectdefs_impl.h \
		../android/qt/5.1.1/gcc/include/QtGui/qwindowdefs_win.h \
		../android/qt/5.1.1/gcc/include/QtCore/qobject.h \
		../android/qt/5.1.1/gcc/include/QtCore/qstring.h \
		../android/qt/5.1.1/gcc/include/QtCore/qchar.h \
		../android/qt/5.1.1/gcc/include/QtCore/qbytearray.h \
		../android/qt/5.1.1/gcc/include/QtCore/qrefcount.h \
		../android/qt/5.1.1/gcc/include/QtCore/qarraydata.h \
		../android/qt/5.1.1/gcc/include/QtCore/qstringbuilder.h \
		../android/qt/5.1.1/gcc/include/QtCore/qlist.h \
		../android/qt/5.1.1/gcc/include/QtCore/qalgorithms.h \
		../android/qt/5.1.1/gcc/include/QtCore/qiterator.h \
		../android/qt/5.1.1/gcc/include/QtCore/qcoreevent.h \
		../android/qt/5.1.1/gcc/include/QtCore/qscopedpointer.h \
		../android/qt/5.1.1/gcc/include/QtCore/qmetatype.h \
		../android/qt/5.1.1/gcc/include/QtCore/qvarlengtharray.h \
		../android/qt/5.1.1/gcc/include/QtCore/qcontainerfwd.h \
		../android/qt/5.1.1/gcc/include/QtCore/qisenum.h \
		../android/qt/5.1.1/gcc/include/QtCore/qobject_impl.h \
		../android/qt/5.1.1/gcc/include/QtCore/qmargins.h \
		../android/qt/5.1.1/gcc/include/QtCore/qrect.h \
		../android/qt/5.1.1/gcc/include/QtCore/qsize.h \
		../android/qt/5.1.1/gcc/include/QtCore/qpoint.h \
		../android/qt/5.1.1/gcc/include/QtGui/qpaintdevice.h \
		../android/qt/5.1.1/gcc/include/QtGui/qpalette.h \
		../android/qt/5.1.1/gcc/include/QtGui/qcolor.h \
		../android/qt/5.1.1/gcc/include/QtGui/qrgb.h \
		../android/qt/5.1.1/gcc/include/QtCore/qstringlist.h \
		../android/qt/5.1.1/gcc/include/QtCore/qdatastream.h \
		../android/qt/5.1.1/gcc/include/QtCore/qiodevice.h \
		../android/qt/5.1.1/gcc/include/QtCore/qpair.h \
		../android/qt/5.1.1/gcc/include/QtCore/qregexp.h \
		../android/qt/5.1.1/gcc/include/QtCore/qstringmatcher.h \
		../android/qt/5.1.1/gcc/include/QtGui/qbrush.h \
		../android/qt/5.1.1/gcc/include/QtCore/qvector.h \
		../android/qt/5.1.1/gcc/include/QtGui/qmatrix.h \
		../android/qt/5.1.1/gcc/include/QtGui/qpolygon.h \
		../android/qt/5.1.1/gcc/include/QtGui/qregion.h \
		../android/qt/5.1.1/gcc/include/QtCore/qline.h \
		../android/qt/5.1.1/gcc/include/QtGui/qtransform.h \
		../android/qt/5.1.1/gcc/include/QtGui/qpainterpath.h \
		../android/qt/5.1.1/gcc/include/QtGui/qimage.h \
		../android/qt/5.1.1/gcc/include/QtGui/qpixmap.h \
		../android/qt/5.1.1/gcc/include/QtCore/qsharedpointer.h \
		../android/qt/5.1.1/gcc/include/QtCore/qshareddata.h \
		../android/qt/5.1.1/gcc/include/QtCore/qsharedpointer_impl.h \
		../android/qt/5.1.1/gcc/include/QtCore/qhash.h \
		../android/qt/5.1.1/gcc/include/QtGui/qfont.h \
		../android/qt/5.1.1/gcc/include/QtGui/qfontmetrics.h \
		../android/qt/5.1.1/gcc/include/QtGui/qfontinfo.h \
		../android/qt/5.1.1/gcc/include/QtWidgets/qsizepolicy.h \
		../android/qt/5.1.1/gcc/include/QtGui/qcursor.h \
		../android/qt/5.1.1/gcc/include/QtGui/qkeysequence.h \
		../android/qt/5.1.1/gcc/include/QtGui/qevent.h \
		../android/qt/5.1.1/gcc/include/QtCore/qvariant.h \
		../android/qt/5.1.1/gcc/include/QtCore/qmap.h \
		../android/qt/5.1.1/gcc/include/QtCore/qdebug.h \
		../android/qt/5.1.1/gcc/include/QtCore/qtextstream.h \
		../android/qt/5.1.1/gcc/include/QtCore/qlocale.h \
		../android/qt/5.1.1/gcc/include/QtCore/qset.h \
		../android/qt/5.1.1/gcc/include/QtCore/qcontiguouscache.h \
		../android/qt/5.1.1/gcc/include/QtCore/qurl.h \
		../android/qt/5.1.1/gcc/include/QtCore/qurlquery.h \
		../android/qt/5.1.1/gcc/include/QtCore/qfile.h \
		../android/qt/5.1.1/gcc/include/QtCore/qfiledevice.h \
		../android/qt/5.1.1/gcc/include/QtGui/qvector2d.h \
		../android/qt/5.1.1/gcc/include/QtGui/qtouchdevice.h \
		mainwindow.h \
		../android/qt/5.1.1/gcc/include/QtWidgets/QMainWindow \
		../android/qt/5.1.1/gcc/include/QtWidgets/qmainwindow.h \
		../android/qt/5.1.1/gcc/include/QtWidgets/qtabwidget.h \
		../android/qt/5.1.1/gcc/include/QtGui/qicon.h \
		../android/qt/5.1.1/gcc/include/QtCore/QDebug \
		../android/qt/5.1.1/gcc/include/QtGui/QPainter \
		../android/qt/5.1.1/gcc/include/QtGui/qpainter.h \
		../android/qt/5.1.1/gcc/include/QtGui/qtextoption.h \
		../android/qt/5.1.1/gcc/include/QtGui/qpen.h \
		../android/qt/5.1.1/gcc/include/QtCore/QRectF \
		pierre.h \
		../android/qt/5.1.1/gcc/include/QtWidgets/QLabel \
		../android/qt/5.1.1/gcc/include/QtWidgets/qlabel.h \
		../android/qt/5.1.1/gcc/include/QtWidgets/qframe.h \
		../android/qt/5.1.1/gcc/include/QtGui/QMouseEvent \
		../android/qt/5.1.1/gcc/include/QtCore/QVector \
		../android/qt/5.1.1/gcc/include/QtGui/QMovie \
		../android/qt/5.1.1/gcc/include/QtGui/qmovie.h \
		../android/qt/5.1.1/gcc/include/QtGui/qimagereader.h \
		../android/qt/5.1.1/gcc/include/QtGui/qimageiohandler.h \
		../android/qt/5.1.1/gcc/include/QtCore/qplugin.h \
		../android/qt/5.1.1/gcc/include/QtCore/qpointer.h \
		../android/qt/5.1.1/gcc/include/QtCore/qfactoryinterface.h \
		../android/qt/5.1.1/gcc/include/QtMultimedia/QMediaPlayer \
		../android/qt/5.1.1/gcc/include/QtMultimedia/qmediaplayer.h \
		../android/qt/5.1.1/gcc/include/QtMultimedia/qmediaobject.h \
		../android/qt/5.1.1/gcc/include/QtMultimedia/qtmultimediadefs.h \
		../android/qt/5.1.1/gcc/include/QtMultimedia/qmultimedia.h \
		../android/qt/5.1.1/gcc/include/QtMultimedia/qmediacontent.h \
		../android/qt/5.1.1/gcc/include/QtMultimedia/qmediaresource.h \
		../android/qt/5.1.1/gcc/include/QtNetwork/qnetworkrequest.h \
		../android/qt/5.1.1/gcc/include/QtCore/QSharedDataPointer \
		../android/qt/5.1.1/gcc/include/QtCore/QString \
		../android/qt/5.1.1/gcc/include/QtCore/QUrl \
		../android/qt/5.1.1/gcc/include/QtCore/QVariant \
		../android/qt/5.1.1/gcc/include/QtMultimedia/qmediaenumdebug.h \
		../android/qt/5.1.1/gcc/include/QtCore/qmetaobject.h \
		../android/qt/5.1.1/gcc/include/QtNetwork/qnetworkconfiguration.h \
		../android/qt/5.1.1/gcc/include/QtMultimedia/QSoundEffect \
		../android/qt/5.1.1/gcc/include/QtMultimedia/qsoundeffect.h \
		dialogtheme.h \
		dialogoption.h \
		../android/qt/5.1.1/gcc/include/QtGui/QPixmap \
		dialogtheme.h
	/home/cyril/android/qt/5.1.1/gcc/bin/moc $(DEFINES) $(INCPATH) dialogtheme.h -o moc_dialogtheme.cpp

moc_dialogoption.cpp: ../android/qt/5.1.1/gcc/include/QtWidgets/QDialog \
		../android/qt/5.1.1/gcc/include/QtWidgets/qdialog.h \
		../android/qt/5.1.1/gcc/include/QtWidgets/qwidget.h \
		../android/qt/5.1.1/gcc/include/QtGui/qwindowdefs.h \
		../android/qt/5.1.1/gcc/include/QtCore/qglobal.h \
		../android/qt/5.1.1/gcc/include/QtCore/qconfig.h \
		../android/qt/5.1.1/gcc/include/QtCore/qfeatures.h \
		../android/qt/5.1.1/gcc/include/QtCore/qsystemdetection.h \
		../android/qt/5.1.1/gcc/include/QtCore/qcompilerdetection.h \
		../android/qt/5.1.1/gcc/include/QtCore/qprocessordetection.h \
		../android/qt/5.1.1/gcc/include/QtCore/qglobalstatic.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic.h \
		../android/qt/5.1.1/gcc/include/QtCore/qbasicatomic.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_bootstrap.h \
		../android/qt/5.1.1/gcc/include/QtCore/qgenericatomic.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_msvc.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_integrity.h \
		../android/qt/5.1.1/gcc/include/QtCore/qoldbasicatomic.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_vxworks.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_power.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_alpha.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_armv7.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_armv6.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_armv5.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_bfin.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_ia64.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_mips.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_s390.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_sh4a.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_sparc.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_x86.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_cxx11.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_gcc.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_unix.h \
		../android/qt/5.1.1/gcc/include/QtCore/qmutex.h \
		../android/qt/5.1.1/gcc/include/QtCore/qlogging.h \
		../android/qt/5.1.1/gcc/include/QtCore/qflags.h \
		../android/qt/5.1.1/gcc/include/QtCore/qtypeinfo.h \
		../android/qt/5.1.1/gcc/include/QtCore/qtypetraits.h \
		../android/qt/5.1.1/gcc/include/QtCore/qsysinfo.h \
		../android/qt/5.1.1/gcc/include/QtCore/qobjectdefs.h \
		../android/qt/5.1.1/gcc/include/QtCore/qnamespace.h \
		../android/qt/5.1.1/gcc/include/QtCore/qobjectdefs_impl.h \
		../android/qt/5.1.1/gcc/include/QtGui/qwindowdefs_win.h \
		../android/qt/5.1.1/gcc/include/QtCore/qobject.h \
		../android/qt/5.1.1/gcc/include/QtCore/qstring.h \
		../android/qt/5.1.1/gcc/include/QtCore/qchar.h \
		../android/qt/5.1.1/gcc/include/QtCore/qbytearray.h \
		../android/qt/5.1.1/gcc/include/QtCore/qrefcount.h \
		../android/qt/5.1.1/gcc/include/QtCore/qarraydata.h \
		../android/qt/5.1.1/gcc/include/QtCore/qstringbuilder.h \
		../android/qt/5.1.1/gcc/include/QtCore/qlist.h \
		../android/qt/5.1.1/gcc/include/QtCore/qalgorithms.h \
		../android/qt/5.1.1/gcc/include/QtCore/qiterator.h \
		../android/qt/5.1.1/gcc/include/QtCore/qcoreevent.h \
		../android/qt/5.1.1/gcc/include/QtCore/qscopedpointer.h \
		../android/qt/5.1.1/gcc/include/QtCore/qmetatype.h \
		../android/qt/5.1.1/gcc/include/QtCore/qvarlengtharray.h \
		../android/qt/5.1.1/gcc/include/QtCore/qcontainerfwd.h \
		../android/qt/5.1.1/gcc/include/QtCore/qisenum.h \
		../android/qt/5.1.1/gcc/include/QtCore/qobject_impl.h \
		../android/qt/5.1.1/gcc/include/QtCore/qmargins.h \
		../android/qt/5.1.1/gcc/include/QtCore/qrect.h \
		../android/qt/5.1.1/gcc/include/QtCore/qsize.h \
		../android/qt/5.1.1/gcc/include/QtCore/qpoint.h \
		../android/qt/5.1.1/gcc/include/QtGui/qpaintdevice.h \
		../android/qt/5.1.1/gcc/include/QtGui/qpalette.h \
		../android/qt/5.1.1/gcc/include/QtGui/qcolor.h \
		../android/qt/5.1.1/gcc/include/QtGui/qrgb.h \
		../android/qt/5.1.1/gcc/include/QtCore/qstringlist.h \
		../android/qt/5.1.1/gcc/include/QtCore/qdatastream.h \
		../android/qt/5.1.1/gcc/include/QtCore/qiodevice.h \
		../android/qt/5.1.1/gcc/include/QtCore/qpair.h \
		../android/qt/5.1.1/gcc/include/QtCore/qregexp.h \
		../android/qt/5.1.1/gcc/include/QtCore/qstringmatcher.h \
		../android/qt/5.1.1/gcc/include/QtGui/qbrush.h \
		../android/qt/5.1.1/gcc/include/QtCore/qvector.h \
		../android/qt/5.1.1/gcc/include/QtGui/qmatrix.h \
		../android/qt/5.1.1/gcc/include/QtGui/qpolygon.h \
		../android/qt/5.1.1/gcc/include/QtGui/qregion.h \
		../android/qt/5.1.1/gcc/include/QtCore/qline.h \
		../android/qt/5.1.1/gcc/include/QtGui/qtransform.h \
		../android/qt/5.1.1/gcc/include/QtGui/qpainterpath.h \
		../android/qt/5.1.1/gcc/include/QtGui/qimage.h \
		../android/qt/5.1.1/gcc/include/QtGui/qpixmap.h \
		../android/qt/5.1.1/gcc/include/QtCore/qsharedpointer.h \
		../android/qt/5.1.1/gcc/include/QtCore/qshareddata.h \
		../android/qt/5.1.1/gcc/include/QtCore/qsharedpointer_impl.h \
		../android/qt/5.1.1/gcc/include/QtCore/qhash.h \
		../android/qt/5.1.1/gcc/include/QtGui/qfont.h \
		../android/qt/5.1.1/gcc/include/QtGui/qfontmetrics.h \
		../android/qt/5.1.1/gcc/include/QtGui/qfontinfo.h \
		../android/qt/5.1.1/gcc/include/QtWidgets/qsizepolicy.h \
		../android/qt/5.1.1/gcc/include/QtGui/qcursor.h \
		../android/qt/5.1.1/gcc/include/QtGui/qkeysequence.h \
		../android/qt/5.1.1/gcc/include/QtGui/qevent.h \
		../android/qt/5.1.1/gcc/include/QtCore/qvariant.h \
		../android/qt/5.1.1/gcc/include/QtCore/qmap.h \
		../android/qt/5.1.1/gcc/include/QtCore/qdebug.h \
		../android/qt/5.1.1/gcc/include/QtCore/qtextstream.h \
		../android/qt/5.1.1/gcc/include/QtCore/qlocale.h \
		../android/qt/5.1.1/gcc/include/QtCore/qset.h \
		../android/qt/5.1.1/gcc/include/QtCore/qcontiguouscache.h \
		../android/qt/5.1.1/gcc/include/QtCore/qurl.h \
		../android/qt/5.1.1/gcc/include/QtCore/qurlquery.h \
		../android/qt/5.1.1/gcc/include/QtCore/qfile.h \
		../android/qt/5.1.1/gcc/include/QtCore/qfiledevice.h \
		../android/qt/5.1.1/gcc/include/QtGui/qvector2d.h \
		../android/qt/5.1.1/gcc/include/QtGui/qtouchdevice.h \
		dialogoption.h
	/home/cyril/android/qt/5.1.1/gcc/bin/moc $(DEFINES) $(INCPATH) dialogoption.h -o moc_dialogoption.cpp

compiler_wayland_code_make_all:
compiler_wayland_code_clean:
compiler_qtwayland_client_code_make_all:
compiler_qtwayland_client_code_clean:
compiler_qtwayland_server_code_make_all:
compiler_qtwayland_server_code_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_dialogtheme.h ui_dialogoption.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_dialogtheme.h ui_dialogoption.h
ui_mainwindow.h: mainwindow.ui
	/home/cyril/android/qt/5.1.1/gcc/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_dialogtheme.h: dialogtheme.ui
	/home/cyril/android/qt/5.1.1/gcc/bin/uic dialogtheme.ui -o ui_dialogtheme.h

ui_dialogoption.h: dialogoption.ui
	/home/cyril/android/qt/5.1.1/gcc/bin/uic dialogoption.ui -o ui_dialogoption.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		../android/qt/5.1.1/gcc/include/QtWidgets/QMainWindow \
		../android/qt/5.1.1/gcc/include/QtWidgets/qmainwindow.h \
		../android/qt/5.1.1/gcc/include/QtWidgets/qwidget.h \
		../android/qt/5.1.1/gcc/include/QtGui/qwindowdefs.h \
		../android/qt/5.1.1/gcc/include/QtCore/qglobal.h \
		../android/qt/5.1.1/gcc/include/QtCore/qconfig.h \
		../android/qt/5.1.1/gcc/include/QtCore/qfeatures.h \
		../android/qt/5.1.1/gcc/include/QtCore/qsystemdetection.h \
		../android/qt/5.1.1/gcc/include/QtCore/qcompilerdetection.h \
		../android/qt/5.1.1/gcc/include/QtCore/qprocessordetection.h \
		../android/qt/5.1.1/gcc/include/QtCore/qglobalstatic.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic.h \
		../android/qt/5.1.1/gcc/include/QtCore/qbasicatomic.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_bootstrap.h \
		../android/qt/5.1.1/gcc/include/QtCore/qgenericatomic.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_msvc.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_integrity.h \
		../android/qt/5.1.1/gcc/include/QtCore/qoldbasicatomic.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_vxworks.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_power.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_alpha.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_armv7.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_armv6.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_armv5.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_bfin.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_ia64.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_mips.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_s390.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_sh4a.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_sparc.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_x86.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_cxx11.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_gcc.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_unix.h \
		../android/qt/5.1.1/gcc/include/QtCore/qmutex.h \
		../android/qt/5.1.1/gcc/include/QtCore/qlogging.h \
		../android/qt/5.1.1/gcc/include/QtCore/qflags.h \
		../android/qt/5.1.1/gcc/include/QtCore/qtypeinfo.h \
		../android/qt/5.1.1/gcc/include/QtCore/qtypetraits.h \
		../android/qt/5.1.1/gcc/include/QtCore/qsysinfo.h \
		../android/qt/5.1.1/gcc/include/QtCore/qobjectdefs.h \
		../android/qt/5.1.1/gcc/include/QtCore/qnamespace.h \
		../android/qt/5.1.1/gcc/include/QtCore/qobjectdefs_impl.h \
		../android/qt/5.1.1/gcc/include/QtGui/qwindowdefs_win.h \
		../android/qt/5.1.1/gcc/include/QtCore/qobject.h \
		../android/qt/5.1.1/gcc/include/QtCore/qstring.h \
		../android/qt/5.1.1/gcc/include/QtCore/qchar.h \
		../android/qt/5.1.1/gcc/include/QtCore/qbytearray.h \
		../android/qt/5.1.1/gcc/include/QtCore/qrefcount.h \
		../android/qt/5.1.1/gcc/include/QtCore/qarraydata.h \
		../android/qt/5.1.1/gcc/include/QtCore/qstringbuilder.h \
		../android/qt/5.1.1/gcc/include/QtCore/qlist.h \
		../android/qt/5.1.1/gcc/include/QtCore/qalgorithms.h \
		../android/qt/5.1.1/gcc/include/QtCore/qiterator.h \
		../android/qt/5.1.1/gcc/include/QtCore/qcoreevent.h \
		../android/qt/5.1.1/gcc/include/QtCore/qscopedpointer.h \
		../android/qt/5.1.1/gcc/include/QtCore/qmetatype.h \
		../android/qt/5.1.1/gcc/include/QtCore/qvarlengtharray.h \
		../android/qt/5.1.1/gcc/include/QtCore/qcontainerfwd.h \
		../android/qt/5.1.1/gcc/include/QtCore/qisenum.h \
		../android/qt/5.1.1/gcc/include/QtCore/qobject_impl.h \
		../android/qt/5.1.1/gcc/include/QtCore/qmargins.h \
		../android/qt/5.1.1/gcc/include/QtCore/qrect.h \
		../android/qt/5.1.1/gcc/include/QtCore/qsize.h \
		../android/qt/5.1.1/gcc/include/QtCore/qpoint.h \
		../android/qt/5.1.1/gcc/include/QtGui/qpaintdevice.h \
		../android/qt/5.1.1/gcc/include/QtGui/qpalette.h \
		../android/qt/5.1.1/gcc/include/QtGui/qcolor.h \
		../android/qt/5.1.1/gcc/include/QtGui/qrgb.h \
		../android/qt/5.1.1/gcc/include/QtCore/qstringlist.h \
		../android/qt/5.1.1/gcc/include/QtCore/qdatastream.h \
		../android/qt/5.1.1/gcc/include/QtCore/qiodevice.h \
		../android/qt/5.1.1/gcc/include/QtCore/qpair.h \
		../android/qt/5.1.1/gcc/include/QtCore/qregexp.h \
		../android/qt/5.1.1/gcc/include/QtCore/qstringmatcher.h \
		../android/qt/5.1.1/gcc/include/QtGui/qbrush.h \
		../android/qt/5.1.1/gcc/include/QtCore/qvector.h \
		../android/qt/5.1.1/gcc/include/QtGui/qmatrix.h \
		../android/qt/5.1.1/gcc/include/QtGui/qpolygon.h \
		../android/qt/5.1.1/gcc/include/QtGui/qregion.h \
		../android/qt/5.1.1/gcc/include/QtCore/qline.h \
		../android/qt/5.1.1/gcc/include/QtGui/qtransform.h \
		../android/qt/5.1.1/gcc/include/QtGui/qpainterpath.h \
		../android/qt/5.1.1/gcc/include/QtGui/qimage.h \
		../android/qt/5.1.1/gcc/include/QtGui/qpixmap.h \
		../android/qt/5.1.1/gcc/include/QtCore/qsharedpointer.h \
		../android/qt/5.1.1/gcc/include/QtCore/qshareddata.h \
		../android/qt/5.1.1/gcc/include/QtCore/qsharedpointer_impl.h \
		../android/qt/5.1.1/gcc/include/QtCore/qhash.h \
		../android/qt/5.1.1/gcc/include/QtGui/qfont.h \
		../android/qt/5.1.1/gcc/include/QtGui/qfontmetrics.h \
		../android/qt/5.1.1/gcc/include/QtGui/qfontinfo.h \
		../android/qt/5.1.1/gcc/include/QtWidgets/qsizepolicy.h \
		../android/qt/5.1.1/gcc/include/QtGui/qcursor.h \
		../android/qt/5.1.1/gcc/include/QtGui/qkeysequence.h \
		../android/qt/5.1.1/gcc/include/QtGui/qevent.h \
		../android/qt/5.1.1/gcc/include/QtCore/qvariant.h \
		../android/qt/5.1.1/gcc/include/QtCore/qmap.h \
		../android/qt/5.1.1/gcc/include/QtCore/qdebug.h \
		../android/qt/5.1.1/gcc/include/QtCore/qtextstream.h \
		../android/qt/5.1.1/gcc/include/QtCore/qlocale.h \
		../android/qt/5.1.1/gcc/include/QtCore/qset.h \
		../android/qt/5.1.1/gcc/include/QtCore/qcontiguouscache.h \
		../android/qt/5.1.1/gcc/include/QtCore/qurl.h \
		../android/qt/5.1.1/gcc/include/QtCore/qurlquery.h \
		../android/qt/5.1.1/gcc/include/QtCore/qfile.h \
		../android/qt/5.1.1/gcc/include/QtCore/qfiledevice.h \
		../android/qt/5.1.1/gcc/include/QtGui/qvector2d.h \
		../android/qt/5.1.1/gcc/include/QtGui/qtouchdevice.h \
		../android/qt/5.1.1/gcc/include/QtWidgets/qtabwidget.h \
		../android/qt/5.1.1/gcc/include/QtGui/qicon.h \
		../android/qt/5.1.1/gcc/include/QtCore/QDebug \
		../android/qt/5.1.1/gcc/include/QtGui/QPainter \
		../android/qt/5.1.1/gcc/include/QtGui/qpainter.h \
		../android/qt/5.1.1/gcc/include/QtGui/qtextoption.h \
		../android/qt/5.1.1/gcc/include/QtGui/qpen.h \
		../android/qt/5.1.1/gcc/include/QtCore/QRectF \
		pierre.h \
		../android/qt/5.1.1/gcc/include/QtWidgets/QLabel \
		../android/qt/5.1.1/gcc/include/QtWidgets/qlabel.h \
		../android/qt/5.1.1/gcc/include/QtWidgets/qframe.h \
		../android/qt/5.1.1/gcc/include/QtGui/QMouseEvent \
		../android/qt/5.1.1/gcc/include/QtCore/QVector \
		../android/qt/5.1.1/gcc/include/QtGui/QMovie \
		../android/qt/5.1.1/gcc/include/QtGui/qmovie.h \
		../android/qt/5.1.1/gcc/include/QtGui/qimagereader.h \
		../android/qt/5.1.1/gcc/include/QtGui/qimageiohandler.h \
		../android/qt/5.1.1/gcc/include/QtCore/qplugin.h \
		../android/qt/5.1.1/gcc/include/QtCore/qpointer.h \
		../android/qt/5.1.1/gcc/include/QtCore/qfactoryinterface.h \
		../android/qt/5.1.1/gcc/include/QtMultimedia/QMediaPlayer \
		../android/qt/5.1.1/gcc/include/QtMultimedia/qmediaplayer.h \
		../android/qt/5.1.1/gcc/include/QtMultimedia/qmediaobject.h \
		../android/qt/5.1.1/gcc/include/QtMultimedia/qtmultimediadefs.h \
		../android/qt/5.1.1/gcc/include/QtMultimedia/qmultimedia.h \
		../android/qt/5.1.1/gcc/include/QtMultimedia/qmediacontent.h \
		../android/qt/5.1.1/gcc/include/QtMultimedia/qmediaresource.h \
		../android/qt/5.1.1/gcc/include/QtNetwork/qnetworkrequest.h \
		../android/qt/5.1.1/gcc/include/QtCore/QSharedDataPointer \
		../android/qt/5.1.1/gcc/include/QtCore/QString \
		../android/qt/5.1.1/gcc/include/QtCore/QUrl \
		../android/qt/5.1.1/gcc/include/QtCore/QVariant \
		../android/qt/5.1.1/gcc/include/QtMultimedia/qmediaenumdebug.h \
		../android/qt/5.1.1/gcc/include/QtCore/qmetaobject.h \
		../android/qt/5.1.1/gcc/include/QtNetwork/qnetworkconfiguration.h \
		../android/qt/5.1.1/gcc/include/QtMultimedia/QSoundEffect \
		../android/qt/5.1.1/gcc/include/QtMultimedia/qsoundeffect.h \
		dialogtheme.h \
		../android/qt/5.1.1/gcc/include/QtWidgets/QDialog \
		../android/qt/5.1.1/gcc/include/QtWidgets/qdialog.h \
		dialogoption.h \
		../android/qt/5.1.1/gcc/include/QtGui/QPixmap \
		../android/qt/5.1.1/gcc/include/QtWidgets/QApplication \
		../android/qt/5.1.1/gcc/include/QtWidgets/qapplication.h \
		../android/qt/5.1.1/gcc/include/QtCore/qcoreapplication.h \
		../android/qt/5.1.1/gcc/include/QtCore/qeventloop.h \
		../android/qt/5.1.1/gcc/include/QtWidgets/qdesktopwidget.h \
		../android/qt/5.1.1/gcc/include/QtGui/qguiapplication.h \
		../android/qt/5.1.1/gcc/include/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		../android/qt/5.1.1/gcc/include/QtWidgets/QMainWindow \
		../android/qt/5.1.1/gcc/include/QtWidgets/qmainwindow.h \
		../android/qt/5.1.1/gcc/include/QtWidgets/qwidget.h \
		../android/qt/5.1.1/gcc/include/QtGui/qwindowdefs.h \
		../android/qt/5.1.1/gcc/include/QtCore/qglobal.h \
		../android/qt/5.1.1/gcc/include/QtCore/qconfig.h \
		../android/qt/5.1.1/gcc/include/QtCore/qfeatures.h \
		../android/qt/5.1.1/gcc/include/QtCore/qsystemdetection.h \
		../android/qt/5.1.1/gcc/include/QtCore/qcompilerdetection.h \
		../android/qt/5.1.1/gcc/include/QtCore/qprocessordetection.h \
		../android/qt/5.1.1/gcc/include/QtCore/qglobalstatic.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic.h \
		../android/qt/5.1.1/gcc/include/QtCore/qbasicatomic.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_bootstrap.h \
		../android/qt/5.1.1/gcc/include/QtCore/qgenericatomic.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_msvc.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_integrity.h \
		../android/qt/5.1.1/gcc/include/QtCore/qoldbasicatomic.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_vxworks.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_power.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_alpha.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_armv7.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_armv6.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_armv5.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_bfin.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_ia64.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_mips.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_s390.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_sh4a.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_sparc.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_x86.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_cxx11.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_gcc.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_unix.h \
		../android/qt/5.1.1/gcc/include/QtCore/qmutex.h \
		../android/qt/5.1.1/gcc/include/QtCore/qlogging.h \
		../android/qt/5.1.1/gcc/include/QtCore/qflags.h \
		../android/qt/5.1.1/gcc/include/QtCore/qtypeinfo.h \
		../android/qt/5.1.1/gcc/include/QtCore/qtypetraits.h \
		../android/qt/5.1.1/gcc/include/QtCore/qsysinfo.h \
		../android/qt/5.1.1/gcc/include/QtCore/qobjectdefs.h \
		../android/qt/5.1.1/gcc/include/QtCore/qnamespace.h \
		../android/qt/5.1.1/gcc/include/QtCore/qobjectdefs_impl.h \
		../android/qt/5.1.1/gcc/include/QtGui/qwindowdefs_win.h \
		../android/qt/5.1.1/gcc/include/QtCore/qobject.h \
		../android/qt/5.1.1/gcc/include/QtCore/qstring.h \
		../android/qt/5.1.1/gcc/include/QtCore/qchar.h \
		../android/qt/5.1.1/gcc/include/QtCore/qbytearray.h \
		../android/qt/5.1.1/gcc/include/QtCore/qrefcount.h \
		../android/qt/5.1.1/gcc/include/QtCore/qarraydata.h \
		../android/qt/5.1.1/gcc/include/QtCore/qstringbuilder.h \
		../android/qt/5.1.1/gcc/include/QtCore/qlist.h \
		../android/qt/5.1.1/gcc/include/QtCore/qalgorithms.h \
		../android/qt/5.1.1/gcc/include/QtCore/qiterator.h \
		../android/qt/5.1.1/gcc/include/QtCore/qcoreevent.h \
		../android/qt/5.1.1/gcc/include/QtCore/qscopedpointer.h \
		../android/qt/5.1.1/gcc/include/QtCore/qmetatype.h \
		../android/qt/5.1.1/gcc/include/QtCore/qvarlengtharray.h \
		../android/qt/5.1.1/gcc/include/QtCore/qcontainerfwd.h \
		../android/qt/5.1.1/gcc/include/QtCore/qisenum.h \
		../android/qt/5.1.1/gcc/include/QtCore/qobject_impl.h \
		../android/qt/5.1.1/gcc/include/QtCore/qmargins.h \
		../android/qt/5.1.1/gcc/include/QtCore/qrect.h \
		../android/qt/5.1.1/gcc/include/QtCore/qsize.h \
		../android/qt/5.1.1/gcc/include/QtCore/qpoint.h \
		../android/qt/5.1.1/gcc/include/QtGui/qpaintdevice.h \
		../android/qt/5.1.1/gcc/include/QtGui/qpalette.h \
		../android/qt/5.1.1/gcc/include/QtGui/qcolor.h \
		../android/qt/5.1.1/gcc/include/QtGui/qrgb.h \
		../android/qt/5.1.1/gcc/include/QtCore/qstringlist.h \
		../android/qt/5.1.1/gcc/include/QtCore/qdatastream.h \
		../android/qt/5.1.1/gcc/include/QtCore/qiodevice.h \
		../android/qt/5.1.1/gcc/include/QtCore/qpair.h \
		../android/qt/5.1.1/gcc/include/QtCore/qregexp.h \
		../android/qt/5.1.1/gcc/include/QtCore/qstringmatcher.h \
		../android/qt/5.1.1/gcc/include/QtGui/qbrush.h \
		../android/qt/5.1.1/gcc/include/QtCore/qvector.h \
		../android/qt/5.1.1/gcc/include/QtGui/qmatrix.h \
		../android/qt/5.1.1/gcc/include/QtGui/qpolygon.h \
		../android/qt/5.1.1/gcc/include/QtGui/qregion.h \
		../android/qt/5.1.1/gcc/include/QtCore/qline.h \
		../android/qt/5.1.1/gcc/include/QtGui/qtransform.h \
		../android/qt/5.1.1/gcc/include/QtGui/qpainterpath.h \
		../android/qt/5.1.1/gcc/include/QtGui/qimage.h \
		../android/qt/5.1.1/gcc/include/QtGui/qpixmap.h \
		../android/qt/5.1.1/gcc/include/QtCore/qsharedpointer.h \
		../android/qt/5.1.1/gcc/include/QtCore/qshareddata.h \
		../android/qt/5.1.1/gcc/include/QtCore/qsharedpointer_impl.h \
		../android/qt/5.1.1/gcc/include/QtCore/qhash.h \
		../android/qt/5.1.1/gcc/include/QtGui/qfont.h \
		../android/qt/5.1.1/gcc/include/QtGui/qfontmetrics.h \
		../android/qt/5.1.1/gcc/include/QtGui/qfontinfo.h \
		../android/qt/5.1.1/gcc/include/QtWidgets/qsizepolicy.h \
		../android/qt/5.1.1/gcc/include/QtGui/qcursor.h \
		../android/qt/5.1.1/gcc/include/QtGui/qkeysequence.h \
		../android/qt/5.1.1/gcc/include/QtGui/qevent.h \
		../android/qt/5.1.1/gcc/include/QtCore/qvariant.h \
		../android/qt/5.1.1/gcc/include/QtCore/qmap.h \
		../android/qt/5.1.1/gcc/include/QtCore/qdebug.h \
		../android/qt/5.1.1/gcc/include/QtCore/qtextstream.h \
		../android/qt/5.1.1/gcc/include/QtCore/qlocale.h \
		../android/qt/5.1.1/gcc/include/QtCore/qset.h \
		../android/qt/5.1.1/gcc/include/QtCore/qcontiguouscache.h \
		../android/qt/5.1.1/gcc/include/QtCore/qurl.h \
		../android/qt/5.1.1/gcc/include/QtCore/qurlquery.h \
		../android/qt/5.1.1/gcc/include/QtCore/qfile.h \
		../android/qt/5.1.1/gcc/include/QtCore/qfiledevice.h \
		../android/qt/5.1.1/gcc/include/QtGui/qvector2d.h \
		../android/qt/5.1.1/gcc/include/QtGui/qtouchdevice.h \
		../android/qt/5.1.1/gcc/include/QtWidgets/qtabwidget.h \
		../android/qt/5.1.1/gcc/include/QtGui/qicon.h \
		../android/qt/5.1.1/gcc/include/QtCore/QDebug \
		../android/qt/5.1.1/gcc/include/QtGui/QPainter \
		../android/qt/5.1.1/gcc/include/QtGui/qpainter.h \
		../android/qt/5.1.1/gcc/include/QtGui/qtextoption.h \
		../android/qt/5.1.1/gcc/include/QtGui/qpen.h \
		../android/qt/5.1.1/gcc/include/QtCore/QRectF \
		pierre.h \
		../android/qt/5.1.1/gcc/include/QtWidgets/QLabel \
		../android/qt/5.1.1/gcc/include/QtWidgets/qlabel.h \
		../android/qt/5.1.1/gcc/include/QtWidgets/qframe.h \
		../android/qt/5.1.1/gcc/include/QtGui/QMouseEvent \
		../android/qt/5.1.1/gcc/include/QtCore/QVector \
		../android/qt/5.1.1/gcc/include/QtGui/QMovie \
		../android/qt/5.1.1/gcc/include/QtGui/qmovie.h \
		../android/qt/5.1.1/gcc/include/QtGui/qimagereader.h \
		../android/qt/5.1.1/gcc/include/QtGui/qimageiohandler.h \
		../android/qt/5.1.1/gcc/include/QtCore/qplugin.h \
		../android/qt/5.1.1/gcc/include/QtCore/qpointer.h \
		../android/qt/5.1.1/gcc/include/QtCore/qfactoryinterface.h \
		../android/qt/5.1.1/gcc/include/QtMultimedia/QMediaPlayer \
		../android/qt/5.1.1/gcc/include/QtMultimedia/qmediaplayer.h \
		../android/qt/5.1.1/gcc/include/QtMultimedia/qmediaobject.h \
		../android/qt/5.1.1/gcc/include/QtMultimedia/qtmultimediadefs.h \
		../android/qt/5.1.1/gcc/include/QtMultimedia/qmultimedia.h \
		../android/qt/5.1.1/gcc/include/QtMultimedia/qmediacontent.h \
		../android/qt/5.1.1/gcc/include/QtMultimedia/qmediaresource.h \
		../android/qt/5.1.1/gcc/include/QtNetwork/qnetworkrequest.h \
		../android/qt/5.1.1/gcc/include/QtCore/QSharedDataPointer \
		../android/qt/5.1.1/gcc/include/QtCore/QString \
		../android/qt/5.1.1/gcc/include/QtCore/QUrl \
		../android/qt/5.1.1/gcc/include/QtCore/QVariant \
		../android/qt/5.1.1/gcc/include/QtMultimedia/qmediaenumdebug.h \
		../android/qt/5.1.1/gcc/include/QtCore/qmetaobject.h \
		../android/qt/5.1.1/gcc/include/QtNetwork/qnetworkconfiguration.h \
		../android/qt/5.1.1/gcc/include/QtMultimedia/QSoundEffect \
		../android/qt/5.1.1/gcc/include/QtMultimedia/qsoundeffect.h \
		dialogtheme.h \
		../android/qt/5.1.1/gcc/include/QtWidgets/QDialog \
		../android/qt/5.1.1/gcc/include/QtWidgets/qdialog.h \
		dialogoption.h \
		../android/qt/5.1.1/gcc/include/QtGui/QPixmap \
		ui_mainwindow.h \
		../android/qt/5.1.1/gcc/include/QtMultimedia/QMediaContent \
		../android/qt/5.1.1/gcc/include/QtWidgets/QMessageBox \
		../android/qt/5.1.1/gcc/include/QtWidgets/qmessagebox.h \
		../android/qt/5.1.1/gcc/include/QtMultimedia/QAudioOutput \
		../android/qt/5.1.1/gcc/include/QtMultimedia/qaudiooutput.h \
		../android/qt/5.1.1/gcc/include/QtMultimedia/qaudio.h \
		../android/qt/5.1.1/gcc/include/QtMultimedia/qaudioformat.h \
		../android/qt/5.1.1/gcc/include/QtMultimedia/qaudiodeviceinfo.h \
		../android/qt/5.1.1/gcc/include/QtWidgets/QStatusBar \
		../android/qt/5.1.1/gcc/include/QtWidgets/qstatusbar.h \
		../android/qt/5.1.1/gcc/include/QtMultimedia/QAudioDeviceInfo
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

pierre.o: pierre.cpp pierre.h \
		../android/qt/5.1.1/gcc/include/QtWidgets/QLabel \
		../android/qt/5.1.1/gcc/include/QtWidgets/qlabel.h \
		../android/qt/5.1.1/gcc/include/QtWidgets/qframe.h \
		../android/qt/5.1.1/gcc/include/QtWidgets/qwidget.h \
		../android/qt/5.1.1/gcc/include/QtGui/qwindowdefs.h \
		../android/qt/5.1.1/gcc/include/QtCore/qglobal.h \
		../android/qt/5.1.1/gcc/include/QtCore/qconfig.h \
		../android/qt/5.1.1/gcc/include/QtCore/qfeatures.h \
		../android/qt/5.1.1/gcc/include/QtCore/qsystemdetection.h \
		../android/qt/5.1.1/gcc/include/QtCore/qcompilerdetection.h \
		../android/qt/5.1.1/gcc/include/QtCore/qprocessordetection.h \
		../android/qt/5.1.1/gcc/include/QtCore/qglobalstatic.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic.h \
		../android/qt/5.1.1/gcc/include/QtCore/qbasicatomic.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_bootstrap.h \
		../android/qt/5.1.1/gcc/include/QtCore/qgenericatomic.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_msvc.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_integrity.h \
		../android/qt/5.1.1/gcc/include/QtCore/qoldbasicatomic.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_vxworks.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_power.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_alpha.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_armv7.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_armv6.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_armv5.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_bfin.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_ia64.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_mips.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_s390.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_sh4a.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_sparc.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_x86.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_cxx11.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_gcc.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_unix.h \
		../android/qt/5.1.1/gcc/include/QtCore/qmutex.h \
		../android/qt/5.1.1/gcc/include/QtCore/qlogging.h \
		../android/qt/5.1.1/gcc/include/QtCore/qflags.h \
		../android/qt/5.1.1/gcc/include/QtCore/qtypeinfo.h \
		../android/qt/5.1.1/gcc/include/QtCore/qtypetraits.h \
		../android/qt/5.1.1/gcc/include/QtCore/qsysinfo.h \
		../android/qt/5.1.1/gcc/include/QtCore/qobjectdefs.h \
		../android/qt/5.1.1/gcc/include/QtCore/qnamespace.h \
		../android/qt/5.1.1/gcc/include/QtCore/qobjectdefs_impl.h \
		../android/qt/5.1.1/gcc/include/QtGui/qwindowdefs_win.h \
		../android/qt/5.1.1/gcc/include/QtCore/qobject.h \
		../android/qt/5.1.1/gcc/include/QtCore/qstring.h \
		../android/qt/5.1.1/gcc/include/QtCore/qchar.h \
		../android/qt/5.1.1/gcc/include/QtCore/qbytearray.h \
		../android/qt/5.1.1/gcc/include/QtCore/qrefcount.h \
		../android/qt/5.1.1/gcc/include/QtCore/qarraydata.h \
		../android/qt/5.1.1/gcc/include/QtCore/qstringbuilder.h \
		../android/qt/5.1.1/gcc/include/QtCore/qlist.h \
		../android/qt/5.1.1/gcc/include/QtCore/qalgorithms.h \
		../android/qt/5.1.1/gcc/include/QtCore/qiterator.h \
		../android/qt/5.1.1/gcc/include/QtCore/qcoreevent.h \
		../android/qt/5.1.1/gcc/include/QtCore/qscopedpointer.h \
		../android/qt/5.1.1/gcc/include/QtCore/qmetatype.h \
		../android/qt/5.1.1/gcc/include/QtCore/qvarlengtharray.h \
		../android/qt/5.1.1/gcc/include/QtCore/qcontainerfwd.h \
		../android/qt/5.1.1/gcc/include/QtCore/qisenum.h \
		../android/qt/5.1.1/gcc/include/QtCore/qobject_impl.h \
		../android/qt/5.1.1/gcc/include/QtCore/qmargins.h \
		../android/qt/5.1.1/gcc/include/QtCore/qrect.h \
		../android/qt/5.1.1/gcc/include/QtCore/qsize.h \
		../android/qt/5.1.1/gcc/include/QtCore/qpoint.h \
		../android/qt/5.1.1/gcc/include/QtGui/qpaintdevice.h \
		../android/qt/5.1.1/gcc/include/QtGui/qpalette.h \
		../android/qt/5.1.1/gcc/include/QtGui/qcolor.h \
		../android/qt/5.1.1/gcc/include/QtGui/qrgb.h \
		../android/qt/5.1.1/gcc/include/QtCore/qstringlist.h \
		../android/qt/5.1.1/gcc/include/QtCore/qdatastream.h \
		../android/qt/5.1.1/gcc/include/QtCore/qiodevice.h \
		../android/qt/5.1.1/gcc/include/QtCore/qpair.h \
		../android/qt/5.1.1/gcc/include/QtCore/qregexp.h \
		../android/qt/5.1.1/gcc/include/QtCore/qstringmatcher.h \
		../android/qt/5.1.1/gcc/include/QtGui/qbrush.h \
		../android/qt/5.1.1/gcc/include/QtCore/qvector.h \
		../android/qt/5.1.1/gcc/include/QtGui/qmatrix.h \
		../android/qt/5.1.1/gcc/include/QtGui/qpolygon.h \
		../android/qt/5.1.1/gcc/include/QtGui/qregion.h \
		../android/qt/5.1.1/gcc/include/QtCore/qline.h \
		../android/qt/5.1.1/gcc/include/QtGui/qtransform.h \
		../android/qt/5.1.1/gcc/include/QtGui/qpainterpath.h \
		../android/qt/5.1.1/gcc/include/QtGui/qimage.h \
		../android/qt/5.1.1/gcc/include/QtGui/qpixmap.h \
		../android/qt/5.1.1/gcc/include/QtCore/qsharedpointer.h \
		../android/qt/5.1.1/gcc/include/QtCore/qshareddata.h \
		../android/qt/5.1.1/gcc/include/QtCore/qsharedpointer_impl.h \
		../android/qt/5.1.1/gcc/include/QtCore/qhash.h \
		../android/qt/5.1.1/gcc/include/QtGui/qfont.h \
		../android/qt/5.1.1/gcc/include/QtGui/qfontmetrics.h \
		../android/qt/5.1.1/gcc/include/QtGui/qfontinfo.h \
		../android/qt/5.1.1/gcc/include/QtWidgets/qsizepolicy.h \
		../android/qt/5.1.1/gcc/include/QtGui/qcursor.h \
		../android/qt/5.1.1/gcc/include/QtGui/qkeysequence.h \
		../android/qt/5.1.1/gcc/include/QtGui/qevent.h \
		../android/qt/5.1.1/gcc/include/QtCore/qvariant.h \
		../android/qt/5.1.1/gcc/include/QtCore/qmap.h \
		../android/qt/5.1.1/gcc/include/QtCore/qdebug.h \
		../android/qt/5.1.1/gcc/include/QtCore/qtextstream.h \
		../android/qt/5.1.1/gcc/include/QtCore/qlocale.h \
		../android/qt/5.1.1/gcc/include/QtCore/qset.h \
		../android/qt/5.1.1/gcc/include/QtCore/qcontiguouscache.h \
		../android/qt/5.1.1/gcc/include/QtCore/qurl.h \
		../android/qt/5.1.1/gcc/include/QtCore/qurlquery.h \
		../android/qt/5.1.1/gcc/include/QtCore/qfile.h \
		../android/qt/5.1.1/gcc/include/QtCore/qfiledevice.h \
		../android/qt/5.1.1/gcc/include/QtGui/qvector2d.h \
		../android/qt/5.1.1/gcc/include/QtGui/qtouchdevice.h \
		../android/qt/5.1.1/gcc/include/QtGui/QMouseEvent \
		../android/qt/5.1.1/gcc/include/QtGui/QPixmap \
		../android/qt/5.1.1/gcc/include/QtCore/QDebug \
		mainwindow.h \
		../android/qt/5.1.1/gcc/include/QtWidgets/QMainWindow \
		../android/qt/5.1.1/gcc/include/QtWidgets/qmainwindow.h \
		../android/qt/5.1.1/gcc/include/QtWidgets/qtabwidget.h \
		../android/qt/5.1.1/gcc/include/QtGui/qicon.h \
		../android/qt/5.1.1/gcc/include/QtGui/QPainter \
		../android/qt/5.1.1/gcc/include/QtGui/qpainter.h \
		../android/qt/5.1.1/gcc/include/QtGui/qtextoption.h \
		../android/qt/5.1.1/gcc/include/QtGui/qpen.h \
		../android/qt/5.1.1/gcc/include/QtCore/QRectF \
		../android/qt/5.1.1/gcc/include/QtCore/QVector \
		../android/qt/5.1.1/gcc/include/QtGui/QMovie \
		../android/qt/5.1.1/gcc/include/QtGui/qmovie.h \
		../android/qt/5.1.1/gcc/include/QtGui/qimagereader.h \
		../android/qt/5.1.1/gcc/include/QtGui/qimageiohandler.h \
		../android/qt/5.1.1/gcc/include/QtCore/qplugin.h \
		../android/qt/5.1.1/gcc/include/QtCore/qpointer.h \
		../android/qt/5.1.1/gcc/include/QtCore/qfactoryinterface.h \
		../android/qt/5.1.1/gcc/include/QtMultimedia/QMediaPlayer \
		../android/qt/5.1.1/gcc/include/QtMultimedia/qmediaplayer.h \
		../android/qt/5.1.1/gcc/include/QtMultimedia/qmediaobject.h \
		../android/qt/5.1.1/gcc/include/QtMultimedia/qtmultimediadefs.h \
		../android/qt/5.1.1/gcc/include/QtMultimedia/qmultimedia.h \
		../android/qt/5.1.1/gcc/include/QtMultimedia/qmediacontent.h \
		../android/qt/5.1.1/gcc/include/QtMultimedia/qmediaresource.h \
		../android/qt/5.1.1/gcc/include/QtNetwork/qnetworkrequest.h \
		../android/qt/5.1.1/gcc/include/QtCore/QSharedDataPointer \
		../android/qt/5.1.1/gcc/include/QtCore/QString \
		../android/qt/5.1.1/gcc/include/QtCore/QUrl \
		../android/qt/5.1.1/gcc/include/QtCore/QVariant \
		../android/qt/5.1.1/gcc/include/QtMultimedia/qmediaenumdebug.h \
		../android/qt/5.1.1/gcc/include/QtCore/qmetaobject.h \
		../android/qt/5.1.1/gcc/include/QtNetwork/qnetworkconfiguration.h \
		../android/qt/5.1.1/gcc/include/QtMultimedia/QSoundEffect \
		../android/qt/5.1.1/gcc/include/QtMultimedia/qsoundeffect.h \
		dialogtheme.h \
		../android/qt/5.1.1/gcc/include/QtWidgets/QDialog \
		../android/qt/5.1.1/gcc/include/QtWidgets/qdialog.h \
		dialogoption.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pierre.o pierre.cpp

dialogtheme.o: dialogtheme.cpp dialogtheme.h \
		../android/qt/5.1.1/gcc/include/QtWidgets/QDialog \
		../android/qt/5.1.1/gcc/include/QtWidgets/qdialog.h \
		../android/qt/5.1.1/gcc/include/QtWidgets/qwidget.h \
		../android/qt/5.1.1/gcc/include/QtGui/qwindowdefs.h \
		../android/qt/5.1.1/gcc/include/QtCore/qglobal.h \
		../android/qt/5.1.1/gcc/include/QtCore/qconfig.h \
		../android/qt/5.1.1/gcc/include/QtCore/qfeatures.h \
		../android/qt/5.1.1/gcc/include/QtCore/qsystemdetection.h \
		../android/qt/5.1.1/gcc/include/QtCore/qcompilerdetection.h \
		../android/qt/5.1.1/gcc/include/QtCore/qprocessordetection.h \
		../android/qt/5.1.1/gcc/include/QtCore/qglobalstatic.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic.h \
		../android/qt/5.1.1/gcc/include/QtCore/qbasicatomic.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_bootstrap.h \
		../android/qt/5.1.1/gcc/include/QtCore/qgenericatomic.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_msvc.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_integrity.h \
		../android/qt/5.1.1/gcc/include/QtCore/qoldbasicatomic.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_vxworks.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_power.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_alpha.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_armv7.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_armv6.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_armv5.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_bfin.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_ia64.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_mips.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_s390.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_sh4a.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_sparc.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_x86.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_cxx11.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_gcc.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_unix.h \
		../android/qt/5.1.1/gcc/include/QtCore/qmutex.h \
		../android/qt/5.1.1/gcc/include/QtCore/qlogging.h \
		../android/qt/5.1.1/gcc/include/QtCore/qflags.h \
		../android/qt/5.1.1/gcc/include/QtCore/qtypeinfo.h \
		../android/qt/5.1.1/gcc/include/QtCore/qtypetraits.h \
		../android/qt/5.1.1/gcc/include/QtCore/qsysinfo.h \
		../android/qt/5.1.1/gcc/include/QtCore/qobjectdefs.h \
		../android/qt/5.1.1/gcc/include/QtCore/qnamespace.h \
		../android/qt/5.1.1/gcc/include/QtCore/qobjectdefs_impl.h \
		../android/qt/5.1.1/gcc/include/QtGui/qwindowdefs_win.h \
		../android/qt/5.1.1/gcc/include/QtCore/qobject.h \
		../android/qt/5.1.1/gcc/include/QtCore/qstring.h \
		../android/qt/5.1.1/gcc/include/QtCore/qchar.h \
		../android/qt/5.1.1/gcc/include/QtCore/qbytearray.h \
		../android/qt/5.1.1/gcc/include/QtCore/qrefcount.h \
		../android/qt/5.1.1/gcc/include/QtCore/qarraydata.h \
		../android/qt/5.1.1/gcc/include/QtCore/qstringbuilder.h \
		../android/qt/5.1.1/gcc/include/QtCore/qlist.h \
		../android/qt/5.1.1/gcc/include/QtCore/qalgorithms.h \
		../android/qt/5.1.1/gcc/include/QtCore/qiterator.h \
		../android/qt/5.1.1/gcc/include/QtCore/qcoreevent.h \
		../android/qt/5.1.1/gcc/include/QtCore/qscopedpointer.h \
		../android/qt/5.1.1/gcc/include/QtCore/qmetatype.h \
		../android/qt/5.1.1/gcc/include/QtCore/qvarlengtharray.h \
		../android/qt/5.1.1/gcc/include/QtCore/qcontainerfwd.h \
		../android/qt/5.1.1/gcc/include/QtCore/qisenum.h \
		../android/qt/5.1.1/gcc/include/QtCore/qobject_impl.h \
		../android/qt/5.1.1/gcc/include/QtCore/qmargins.h \
		../android/qt/5.1.1/gcc/include/QtCore/qrect.h \
		../android/qt/5.1.1/gcc/include/QtCore/qsize.h \
		../android/qt/5.1.1/gcc/include/QtCore/qpoint.h \
		../android/qt/5.1.1/gcc/include/QtGui/qpaintdevice.h \
		../android/qt/5.1.1/gcc/include/QtGui/qpalette.h \
		../android/qt/5.1.1/gcc/include/QtGui/qcolor.h \
		../android/qt/5.1.1/gcc/include/QtGui/qrgb.h \
		../android/qt/5.1.1/gcc/include/QtCore/qstringlist.h \
		../android/qt/5.1.1/gcc/include/QtCore/qdatastream.h \
		../android/qt/5.1.1/gcc/include/QtCore/qiodevice.h \
		../android/qt/5.1.1/gcc/include/QtCore/qpair.h \
		../android/qt/5.1.1/gcc/include/QtCore/qregexp.h \
		../android/qt/5.1.1/gcc/include/QtCore/qstringmatcher.h \
		../android/qt/5.1.1/gcc/include/QtGui/qbrush.h \
		../android/qt/5.1.1/gcc/include/QtCore/qvector.h \
		../android/qt/5.1.1/gcc/include/QtGui/qmatrix.h \
		../android/qt/5.1.1/gcc/include/QtGui/qpolygon.h \
		../android/qt/5.1.1/gcc/include/QtGui/qregion.h \
		../android/qt/5.1.1/gcc/include/QtCore/qline.h \
		../android/qt/5.1.1/gcc/include/QtGui/qtransform.h \
		../android/qt/5.1.1/gcc/include/QtGui/qpainterpath.h \
		../android/qt/5.1.1/gcc/include/QtGui/qimage.h \
		../android/qt/5.1.1/gcc/include/QtGui/qpixmap.h \
		../android/qt/5.1.1/gcc/include/QtCore/qsharedpointer.h \
		../android/qt/5.1.1/gcc/include/QtCore/qshareddata.h \
		../android/qt/5.1.1/gcc/include/QtCore/qsharedpointer_impl.h \
		../android/qt/5.1.1/gcc/include/QtCore/qhash.h \
		../android/qt/5.1.1/gcc/include/QtGui/qfont.h \
		../android/qt/5.1.1/gcc/include/QtGui/qfontmetrics.h \
		../android/qt/5.1.1/gcc/include/QtGui/qfontinfo.h \
		../android/qt/5.1.1/gcc/include/QtWidgets/qsizepolicy.h \
		../android/qt/5.1.1/gcc/include/QtGui/qcursor.h \
		../android/qt/5.1.1/gcc/include/QtGui/qkeysequence.h \
		../android/qt/5.1.1/gcc/include/QtGui/qevent.h \
		../android/qt/5.1.1/gcc/include/QtCore/qvariant.h \
		../android/qt/5.1.1/gcc/include/QtCore/qmap.h \
		../android/qt/5.1.1/gcc/include/QtCore/qdebug.h \
		../android/qt/5.1.1/gcc/include/QtCore/qtextstream.h \
		../android/qt/5.1.1/gcc/include/QtCore/qlocale.h \
		../android/qt/5.1.1/gcc/include/QtCore/qset.h \
		../android/qt/5.1.1/gcc/include/QtCore/qcontiguouscache.h \
		../android/qt/5.1.1/gcc/include/QtCore/qurl.h \
		../android/qt/5.1.1/gcc/include/QtCore/qurlquery.h \
		../android/qt/5.1.1/gcc/include/QtCore/qfile.h \
		../android/qt/5.1.1/gcc/include/QtCore/qfiledevice.h \
		../android/qt/5.1.1/gcc/include/QtGui/qvector2d.h \
		../android/qt/5.1.1/gcc/include/QtGui/qtouchdevice.h \
		mainwindow.h \
		../android/qt/5.1.1/gcc/include/QtWidgets/QMainWindow \
		../android/qt/5.1.1/gcc/include/QtWidgets/qmainwindow.h \
		../android/qt/5.1.1/gcc/include/QtWidgets/qtabwidget.h \
		../android/qt/5.1.1/gcc/include/QtGui/qicon.h \
		../android/qt/5.1.1/gcc/include/QtCore/QDebug \
		../android/qt/5.1.1/gcc/include/QtGui/QPainter \
		../android/qt/5.1.1/gcc/include/QtGui/qpainter.h \
		../android/qt/5.1.1/gcc/include/QtGui/qtextoption.h \
		../android/qt/5.1.1/gcc/include/QtGui/qpen.h \
		../android/qt/5.1.1/gcc/include/QtCore/QRectF \
		pierre.h \
		../android/qt/5.1.1/gcc/include/QtWidgets/QLabel \
		../android/qt/5.1.1/gcc/include/QtWidgets/qlabel.h \
		../android/qt/5.1.1/gcc/include/QtWidgets/qframe.h \
		../android/qt/5.1.1/gcc/include/QtGui/QMouseEvent \
		../android/qt/5.1.1/gcc/include/QtCore/QVector \
		../android/qt/5.1.1/gcc/include/QtGui/QMovie \
		../android/qt/5.1.1/gcc/include/QtGui/qmovie.h \
		../android/qt/5.1.1/gcc/include/QtGui/qimagereader.h \
		../android/qt/5.1.1/gcc/include/QtGui/qimageiohandler.h \
		../android/qt/5.1.1/gcc/include/QtCore/qplugin.h \
		../android/qt/5.1.1/gcc/include/QtCore/qpointer.h \
		../android/qt/5.1.1/gcc/include/QtCore/qfactoryinterface.h \
		../android/qt/5.1.1/gcc/include/QtMultimedia/QMediaPlayer \
		../android/qt/5.1.1/gcc/include/QtMultimedia/qmediaplayer.h \
		../android/qt/5.1.1/gcc/include/QtMultimedia/qmediaobject.h \
		../android/qt/5.1.1/gcc/include/QtMultimedia/qtmultimediadefs.h \
		../android/qt/5.1.1/gcc/include/QtMultimedia/qmultimedia.h \
		../android/qt/5.1.1/gcc/include/QtMultimedia/qmediacontent.h \
		../android/qt/5.1.1/gcc/include/QtMultimedia/qmediaresource.h \
		../android/qt/5.1.1/gcc/include/QtNetwork/qnetworkrequest.h \
		../android/qt/5.1.1/gcc/include/QtCore/QSharedDataPointer \
		../android/qt/5.1.1/gcc/include/QtCore/QString \
		../android/qt/5.1.1/gcc/include/QtCore/QUrl \
		../android/qt/5.1.1/gcc/include/QtCore/QVariant \
		../android/qt/5.1.1/gcc/include/QtMultimedia/qmediaenumdebug.h \
		../android/qt/5.1.1/gcc/include/QtCore/qmetaobject.h \
		../android/qt/5.1.1/gcc/include/QtNetwork/qnetworkconfiguration.h \
		../android/qt/5.1.1/gcc/include/QtMultimedia/QSoundEffect \
		../android/qt/5.1.1/gcc/include/QtMultimedia/qsoundeffect.h \
		dialogoption.h \
		../android/qt/5.1.1/gcc/include/QtGui/QPixmap \
		ui_dialogtheme.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dialogtheme.o dialogtheme.cpp

dialogoption.o: dialogoption.cpp dialogoption.h \
		../android/qt/5.1.1/gcc/include/QtWidgets/QDialog \
		../android/qt/5.1.1/gcc/include/QtWidgets/qdialog.h \
		../android/qt/5.1.1/gcc/include/QtWidgets/qwidget.h \
		../android/qt/5.1.1/gcc/include/QtGui/qwindowdefs.h \
		../android/qt/5.1.1/gcc/include/QtCore/qglobal.h \
		../android/qt/5.1.1/gcc/include/QtCore/qconfig.h \
		../android/qt/5.1.1/gcc/include/QtCore/qfeatures.h \
		../android/qt/5.1.1/gcc/include/QtCore/qsystemdetection.h \
		../android/qt/5.1.1/gcc/include/QtCore/qcompilerdetection.h \
		../android/qt/5.1.1/gcc/include/QtCore/qprocessordetection.h \
		../android/qt/5.1.1/gcc/include/QtCore/qglobalstatic.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic.h \
		../android/qt/5.1.1/gcc/include/QtCore/qbasicatomic.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_bootstrap.h \
		../android/qt/5.1.1/gcc/include/QtCore/qgenericatomic.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_msvc.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_integrity.h \
		../android/qt/5.1.1/gcc/include/QtCore/qoldbasicatomic.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_vxworks.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_power.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_alpha.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_armv7.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_armv6.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_armv5.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_bfin.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_ia64.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_mips.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_s390.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_sh4a.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_sparc.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_x86.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_cxx11.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_gcc.h \
		../android/qt/5.1.1/gcc/include/QtCore/qatomic_unix.h \
		../android/qt/5.1.1/gcc/include/QtCore/qmutex.h \
		../android/qt/5.1.1/gcc/include/QtCore/qlogging.h \
		../android/qt/5.1.1/gcc/include/QtCore/qflags.h \
		../android/qt/5.1.1/gcc/include/QtCore/qtypeinfo.h \
		../android/qt/5.1.1/gcc/include/QtCore/qtypetraits.h \
		../android/qt/5.1.1/gcc/include/QtCore/qsysinfo.h \
		../android/qt/5.1.1/gcc/include/QtCore/qobjectdefs.h \
		../android/qt/5.1.1/gcc/include/QtCore/qnamespace.h \
		../android/qt/5.1.1/gcc/include/QtCore/qobjectdefs_impl.h \
		../android/qt/5.1.1/gcc/include/QtGui/qwindowdefs_win.h \
		../android/qt/5.1.1/gcc/include/QtCore/qobject.h \
		../android/qt/5.1.1/gcc/include/QtCore/qstring.h \
		../android/qt/5.1.1/gcc/include/QtCore/qchar.h \
		../android/qt/5.1.1/gcc/include/QtCore/qbytearray.h \
		../android/qt/5.1.1/gcc/include/QtCore/qrefcount.h \
		../android/qt/5.1.1/gcc/include/QtCore/qarraydata.h \
		../android/qt/5.1.1/gcc/include/QtCore/qstringbuilder.h \
		../android/qt/5.1.1/gcc/include/QtCore/qlist.h \
		../android/qt/5.1.1/gcc/include/QtCore/qalgorithms.h \
		../android/qt/5.1.1/gcc/include/QtCore/qiterator.h \
		../android/qt/5.1.1/gcc/include/QtCore/qcoreevent.h \
		../android/qt/5.1.1/gcc/include/QtCore/qscopedpointer.h \
		../android/qt/5.1.1/gcc/include/QtCore/qmetatype.h \
		../android/qt/5.1.1/gcc/include/QtCore/qvarlengtharray.h \
		../android/qt/5.1.1/gcc/include/QtCore/qcontainerfwd.h \
		../android/qt/5.1.1/gcc/include/QtCore/qisenum.h \
		../android/qt/5.1.1/gcc/include/QtCore/qobject_impl.h \
		../android/qt/5.1.1/gcc/include/QtCore/qmargins.h \
		../android/qt/5.1.1/gcc/include/QtCore/qrect.h \
		../android/qt/5.1.1/gcc/include/QtCore/qsize.h \
		../android/qt/5.1.1/gcc/include/QtCore/qpoint.h \
		../android/qt/5.1.1/gcc/include/QtGui/qpaintdevice.h \
		../android/qt/5.1.1/gcc/include/QtGui/qpalette.h \
		../android/qt/5.1.1/gcc/include/QtGui/qcolor.h \
		../android/qt/5.1.1/gcc/include/QtGui/qrgb.h \
		../android/qt/5.1.1/gcc/include/QtCore/qstringlist.h \
		../android/qt/5.1.1/gcc/include/QtCore/qdatastream.h \
		../android/qt/5.1.1/gcc/include/QtCore/qiodevice.h \
		../android/qt/5.1.1/gcc/include/QtCore/qpair.h \
		../android/qt/5.1.1/gcc/include/QtCore/qregexp.h \
		../android/qt/5.1.1/gcc/include/QtCore/qstringmatcher.h \
		../android/qt/5.1.1/gcc/include/QtGui/qbrush.h \
		../android/qt/5.1.1/gcc/include/QtCore/qvector.h \
		../android/qt/5.1.1/gcc/include/QtGui/qmatrix.h \
		../android/qt/5.1.1/gcc/include/QtGui/qpolygon.h \
		../android/qt/5.1.1/gcc/include/QtGui/qregion.h \
		../android/qt/5.1.1/gcc/include/QtCore/qline.h \
		../android/qt/5.1.1/gcc/include/QtGui/qtransform.h \
		../android/qt/5.1.1/gcc/include/QtGui/qpainterpath.h \
		../android/qt/5.1.1/gcc/include/QtGui/qimage.h \
		../android/qt/5.1.1/gcc/include/QtGui/qpixmap.h \
		../android/qt/5.1.1/gcc/include/QtCore/qsharedpointer.h \
		../android/qt/5.1.1/gcc/include/QtCore/qshareddata.h \
		../android/qt/5.1.1/gcc/include/QtCore/qsharedpointer_impl.h \
		../android/qt/5.1.1/gcc/include/QtCore/qhash.h \
		../android/qt/5.1.1/gcc/include/QtGui/qfont.h \
		../android/qt/5.1.1/gcc/include/QtGui/qfontmetrics.h \
		../android/qt/5.1.1/gcc/include/QtGui/qfontinfo.h \
		../android/qt/5.1.1/gcc/include/QtWidgets/qsizepolicy.h \
		../android/qt/5.1.1/gcc/include/QtGui/qcursor.h \
		../android/qt/5.1.1/gcc/include/QtGui/qkeysequence.h \
		../android/qt/5.1.1/gcc/include/QtGui/qevent.h \
		../android/qt/5.1.1/gcc/include/QtCore/qvariant.h \
		../android/qt/5.1.1/gcc/include/QtCore/qmap.h \
		../android/qt/5.1.1/gcc/include/QtCore/qdebug.h \
		../android/qt/5.1.1/gcc/include/QtCore/qtextstream.h \
		../android/qt/5.1.1/gcc/include/QtCore/qlocale.h \
		../android/qt/5.1.1/gcc/include/QtCore/qset.h \
		../android/qt/5.1.1/gcc/include/QtCore/qcontiguouscache.h \
		../android/qt/5.1.1/gcc/include/QtCore/qurl.h \
		../android/qt/5.1.1/gcc/include/QtCore/qurlquery.h \
		../android/qt/5.1.1/gcc/include/QtCore/qfile.h \
		../android/qt/5.1.1/gcc/include/QtCore/qfiledevice.h \
		../android/qt/5.1.1/gcc/include/QtGui/qvector2d.h \
		../android/qt/5.1.1/gcc/include/QtGui/qtouchdevice.h \
		ui_dialogoption.h \
		../android/qt/5.1.1/gcc/include/QtCore/QVariant \
		mainwindow.h \
		../android/qt/5.1.1/gcc/include/QtWidgets/QMainWindow \
		../android/qt/5.1.1/gcc/include/QtWidgets/qmainwindow.h \
		../android/qt/5.1.1/gcc/include/QtWidgets/qtabwidget.h \
		../android/qt/5.1.1/gcc/include/QtGui/qicon.h \
		../android/qt/5.1.1/gcc/include/QtCore/QDebug \
		../android/qt/5.1.1/gcc/include/QtGui/QPainter \
		../android/qt/5.1.1/gcc/include/QtGui/qpainter.h \
		../android/qt/5.1.1/gcc/include/QtGui/qtextoption.h \
		../android/qt/5.1.1/gcc/include/QtGui/qpen.h \
		../android/qt/5.1.1/gcc/include/QtCore/QRectF \
		pierre.h \
		../android/qt/5.1.1/gcc/include/QtWidgets/QLabel \
		../android/qt/5.1.1/gcc/include/QtWidgets/qlabel.h \
		../android/qt/5.1.1/gcc/include/QtWidgets/qframe.h \
		../android/qt/5.1.1/gcc/include/QtGui/QMouseEvent \
		../android/qt/5.1.1/gcc/include/QtCore/QVector \
		../android/qt/5.1.1/gcc/include/QtGui/QMovie \
		../android/qt/5.1.1/gcc/include/QtGui/qmovie.h \
		../android/qt/5.1.1/gcc/include/QtGui/qimagereader.h \
		../android/qt/5.1.1/gcc/include/QtGui/qimageiohandler.h \
		../android/qt/5.1.1/gcc/include/QtCore/qplugin.h \
		../android/qt/5.1.1/gcc/include/QtCore/qpointer.h \
		../android/qt/5.1.1/gcc/include/QtCore/qfactoryinterface.h \
		../android/qt/5.1.1/gcc/include/QtMultimedia/QMediaPlayer \
		../android/qt/5.1.1/gcc/include/QtMultimedia/qmediaplayer.h \
		../android/qt/5.1.1/gcc/include/QtMultimedia/qmediaobject.h \
		../android/qt/5.1.1/gcc/include/QtMultimedia/qtmultimediadefs.h \
		../android/qt/5.1.1/gcc/include/QtMultimedia/qmultimedia.h \
		../android/qt/5.1.1/gcc/include/QtMultimedia/qmediacontent.h \
		../android/qt/5.1.1/gcc/include/QtMultimedia/qmediaresource.h \
		../android/qt/5.1.1/gcc/include/QtNetwork/qnetworkrequest.h \
		../android/qt/5.1.1/gcc/include/QtCore/QSharedDataPointer \
		../android/qt/5.1.1/gcc/include/QtCore/QString \
		../android/qt/5.1.1/gcc/include/QtCore/QUrl \
		../android/qt/5.1.1/gcc/include/QtMultimedia/qmediaenumdebug.h \
		../android/qt/5.1.1/gcc/include/QtCore/qmetaobject.h \
		../android/qt/5.1.1/gcc/include/QtNetwork/qnetworkconfiguration.h \
		../android/qt/5.1.1/gcc/include/QtMultimedia/QSoundEffect \
		../android/qt/5.1.1/gcc/include/QtMultimedia/qsoundeffect.h \
		dialogtheme.h \
		../android/qt/5.1.1/gcc/include/QtGui/QPixmap
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dialogoption.o dialogoption.cpp

qrc_Images.o: qrc_Images.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_Images.o qrc_Images.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_pierre.o: moc_pierre.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pierre.o moc_pierre.cpp

moc_dialogtheme.o: moc_dialogtheme.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dialogtheme.o moc_dialogtheme.cpp

moc_dialogoption.o: moc_dialogoption.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dialogoption.o moc_dialogoption.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

